Fix linking issue (missing wayland-client library)
flutter/engine pull request #21408
Opened 2020-09-25 13:08 UTC by dwrobel

Linking libflutter_linux_gtk.so shared library fails on
embedded platform as follows:

 fl_renderer_wayland_dispose(_GObject*):
	error: undefined reference to 'wl_proxy_destroy'
 fl_renderer_wayland_dispose(_GObject*):
	error: undefined reference to 'wl_proxy_marshal'
 fl_renderer_wayland_dispose(_GObject*):
	error: undefined reference to 'wl_proxy_destroy'
 fl_renderer_wayland_dispose(_GObject*):
	error: undefined reference to 'wl_proxy_marshal'
 fl_renderer_wayland_dispose(_GObject*):
	error: undefined reference to 'wl_proxy_destroy'
 fl_renderer_wayland_dispose(_GObject*):
	error: undefined reference to 'wl_proxy_marshal'
 fl_renderer_wayland_dispose(_GObject*):
	error: undefined reference to 'wl_proxy_destroy'
 fl_renderer_wayland_dispose(_GObject*):
	error: undefined reference to 'wl_proxy_marshal'
 fl_renderer_wayland_create_surfaces(_FlRenderer*, _GtkWidget*, void*, void*, void**, void**, _GError**):
	error: undefined reference to 'wl_proxy_marshal_constructor'
 fl_renderer_wayland_create_surfaces(_FlRenderer*, _GtkWidget*, void*, void*, void**, void**, _GError**):
	error: undefined reference to 'wl_proxy_marshal_constructor'
 fl_renderer_wayland_create_surfaces(_FlRenderer*, _GtkWidget*, void*, void*, void**, void**, _GError**):
	error: undefined reference to 'wl_surface_interface'
 fl_renderer_wayland_on_window_map(_FlRendererWayland*, _GtkWidget*):
	error: undefined reference to 'wl_proxy_marshal_constructor'
 fl_renderer_wayland_on_window_map(_FlRendererWayland*, _GtkWidget*):
	error: undefined reference to 'wl_proxy_add_listener'
 fl_renderer_wayland_on_window_map(_FlRendererWayland*, _GtkWidget*):
	error: undefined reference to 'wl_display_roundtrip'
 fl_renderer_wayland_on_window_map(_FlRendererWayland*, _GtkWidget*):
	error: undefined reference to 'wl_proxy_marshal_constructor'
 fl_renderer_wayland_on_window_map(_FlRendererWayland*, _GtkWidget*):
	error: undefined reference to 'wl_registry_interface'
 fl_renderer_wayland_on_window_map(_FlRendererWayland*, _GtkWidget*):
	error: undefined reference to 'wl_subsurface_interface'
 fl_renderer_wayland_on_window_map(_FlRendererWayland*, _GtkWidget*):
	error: undefined reference to 'wl_region_interface'
 registry_handle_global(void*, wl_registry*, unsigned int, char const*, unsigned int):
	error: undefined reference to 'wl_proxy_marshal_constructor_versioned'
 registry_handle_global(void*, wl_registry*, unsigned int, char const*, unsigned int):
	error: undefined reference to 'wl_subcompositor_interface'

As fl_renderer_wayland.cc uses directly some of the wayland-client
related functions it should also add this library as a dependency.

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>

## Description

*Replace this paragraph with a description of what this PR is doing. If you're
modifying existing behavior, describe the existing behavior, how this PR is
changing it, and what motivated the change.*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from our [issue
database]. Indicate, which of these issues are resolved or fixed by this PR.
There should be at least one issue listed here.*

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A
change in behaviour with no test covering it will likely get reverted
accidentally sooner or later. PRs must include tests for all
changed/updated/fixed behaviors. See [testing the engine] for instructions on
writing and running engine tests.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [ ] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation.
- [ ] All existing and new tests are passing.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

2020-10-08 21:44 UTC, chinmaygarde commented
cc @stuartmorgan. This looks fine to me but I am not sure if this target is built on CI. Can you please confirm and land?

2020-10-08 21:55 UTC, stuartmorgan requested changes

2020-10-08 21:55 UTC, stuartmorgan commented on shell/platform/linux/config/BUILD.gn
> +    "wayland-client",
wayland-client should not be part of this config, it should be its own config which the relevant target includes.

2020-10-08 21:59 UTC, stuartmorgan commented
Also, I'm confused as to what exactly the repro case here is. Are you building with your own sysroot? If there are missing configurations I would have expected this to fail on the bots.

2020-10-09 08:17 UTC, dwrobel commented
I'm building flutter for Fedora32 _(where I don't observe this linking issue)_ and for embedded platform using [Yocto](https://old.yoctoproject.org/about) where I'm observing the issue.

In Fedora 32 we have the following list of `NEEDED` for `libgtk-3.so`:
```
$ readelf -d /usr/lib64/libgtk-3.so | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libgdk-3.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgmodule-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpangocairo-1.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXi.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libXfixes.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libcairo-gobject.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libcairo.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libgdk_pixbuf-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libatk-1.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libatk-bridge-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libwayland-client.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libepoxy.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libfribidi.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgio-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpangoft2-1.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpango-1.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libgobject-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libglib-2.0.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libharfbuzz.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libfontconfig.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libfreetype.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
```
On the other hand on the `Yocto` we have:
```
$ readelf -d libgtk-3.so | grep NEEDED
 0x00000001 (NEEDED)                     Shared library: [libgdk-3.so.0]
 0x00000001 (NEEDED)                     Shared library: [libpangocairo-1.0.so.0]
 0x00000001 (NEEDED)                     Shared library: [libcairo-gobject.so.2]
 0x00000001 (NEEDED)                     Shared library: [libcairo.so.2]
 0x00000001 (NEEDED)                     Shared library: [libpthread.so.0]
 0x00000001 (NEEDED)                     Shared library: [libgdk_pixbuf-2.0.so.0]
 0x00000001 (NEEDED)                     Shared library: [libgmodule-2.0.so.0]
 0x00000001 (NEEDED)                     Shared library: [libatk-1.0.so.0]
 0x00000001 (NEEDED)                     Shared library: [libepoxy.so.0]
 0x00000001 (NEEDED)                     Shared library: [libfribidi.so.0]
 0x00000001 (NEEDED)                     Shared library: [libgio-2.0.so.0]
 0x00000001 (NEEDED)                     Shared library: [libpangoft2-1.0.so.0]
 0x00000001 (NEEDED)                     Shared library: [libpango-1.0.so.0]
 0x00000001 (NEEDED)                     Shared library: [libgobject-2.0.so.0]
 0x00000001 (NEEDED)                     Shared library: [libharfbuzz.so.0]
 0x00000001 (NEEDED)                     Shared library: [libglib-2.0.so.0]
 0x00000001 (NEEDED)                     Shared library: [libfontconfig.so.1]
 0x00000001 (NEEDED)                     Shared library: [libfreetype.so.6]
 0x00000001 (NEEDED)                     Shared library: [libm.so.6]
 0x00000001 (NEEDED)                     Shared library: [libc.so.6]
 0x00000001 (NEEDED)                     Shared library: [ld-linux-armhf.so.3]
```

The notable difference is that `Yocto` version lacks of:
```
(NEEDED)             Shared library: [libwayland-client.so.0]
```

The difference between linker options across Fedora 32 and Yocto is that the latter uses: `-Wl,--as-needed`.

So, in my opinion and because `libflutter_linux_gtk.so` requires unconditionally `wayland-client` library it shouldn't depend on `libgtk-3.so` to satisfy this link dependency but itself should link using `waylad-client`. This is basically what this PR tries to solve.

2020-10-13 20:25 UTC, stuartmorgan commented
@wmww @robert-ancell Any concerns with adding this to the explicit dependency list?

2020-10-13 21:13 UTC, robert-ancell commented
> @wmww @robert-ancell Any concerns with adding this to the explicit dependency list?

We are making direct Wayland calls, so it should be an explicit dependency.

2020-10-13 21:23 UTC, stuartmorgan commented
Sounds good. @dwrobel, if you address my earlier review comment we can get this landed.

2020-10-14 09:04 UTC, dwrobel commented
> Sounds good. @dwrobel, if you address my earlier review comment we can get this landed.

I created a separate config, please let me know if this is what you had in mind.

2020-10-14 16:11 UTC, stuartmorgan approved these changes
LGTM

2020-10-15 21:35 UTC, chinmaygarde commented
The presubmit error has been fixed on ToT. Can you please rebase and land this patch?

2020-10-20 09:41 UTC, dwrobel commented
> The presubmit error has been fixed on ToT. Can you please rebase and land this patch?

Rebased.

2020-10-20 12:47 UTC, merged