Fix viewInset.bottom and viewPadding.bottom…
flutter/engine pull request #21730
Opened 2020-10-09 15:00 UTC by lazylazyllama

… for pre android api 30 devices

## Description

Currently the flutter engine sets the bottom inset for the navigation bar into `viewInset.bottom` and `viewpadding.bottom` is always 0 on pre api 30 devices.

If you are using edge-to-edge on api 30 everything works perfectly fine, but on api 29, which is supporting edge-to-edge, we get some issues:

The `padding.bottom` value is calculated like this: `max(0, (viewPadding.bottom - viewInset.bottom))`
But if `viewPadding.bottom` is 0 and `viewInset.bottom` contains the system navigation bar height, the resulting `padding.bottom` will be 0.

So for example the `BottomNavigationBar` widget will not apply bottom padding to have its content on over and not behind the system navigation bar.

## Related Issues

- [Android 10] Unable to set transparent navigation bar (flutter/flutter#40974)
- Android 10 incorrect insets when navigation bar is translucent (flutter/flutter#63761)
- [Android Q] Transparent navigation bar with extended scaffold (flutter/flutter#34678 )
- Gallery should implement full screen / edge-to-edge for Android Q+ devices (flutter/flutter#39061)
- Flutter doesn't have a way to handle bottom view insets/notches on Android devices (flutter/flutter#35404)

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A
change in behaviour with no test covering it will likely get reverted
accidentally sooner or later. PRs must include tests for all
changed/updated/fixed behaviors. See [testing the engine] for instructions on
writing and running engine tests.*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation.
- [ ] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Reviewer Checklist

- [ ] I have submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

2020-10-09 15:06 UTC, lazylazyllama commented
The pr is ready for review.

@GaryQian can you review this?

2020-10-13 02:45 UTC, GaryQian commented
This does indeed look like it brings the behavior in line with what is described in https://api.flutter.dev/flutter/widgets/MediaQueryData-class.html. Thanks for the catch.

2020-10-13 02:46 UTC, GaryQian commented
The change will also need to be replicated in the equivalent code in `shell/platform/android/io/flutter/view/FlutterView.java`

2020-10-13 02:48 UTC, GaryQian commented
This PR also needs tests. The best place to put it would probably be in `shell/platform/android/test/io/flutter/embedding/android/FlutterViewTest.java`, where `systemInsetGetInsetsFullscreenLegacy` is likely a good example test to base a new one off of.

2020-10-13 02:48 UTC, GaryQian requested changes
See comments above :)

2020-10-13 06:00 UTC, lazylazyllama commented
Okay thanks for the review. :)

I will look into it this afternoon

2020-10-13 18:02 UTC, lazylazyllama commented
@GaryQian 

I updated all the files based on your feedback.

Regarding the tests, I think that the tests that the available tests should cover my pr, so I only updated them to expect the correct bottomPadding values.

Unfortunately I am struggling, getting the engine compiled and running the tests on my windows pc, so I could not check if my changes to the test file are correct. Would you like to do that? :) If you don't have enough time, I would try to things working on my side, but I don't know how long this will take

2020-10-19 22:25 UTC, GaryQian commented
I may be able to find some time to look at the tests later this week. In the meantime, it should be possible to look at the pre-submit check logs for details on why tests failed. The relevant tests will generally finish running/fail about 10 min after pushing.

You should make sure the tests are changed only for the tests specified for API 29 or below.

2020-10-21 14:25 UTC, lazylazyllama commented
> I may be able to find some time to look at the tests later this week. In the meantime, it should be possible to look at the pre-submit check logs for details on why tests failed. The relevant tests will generally finish running/fail about 10 min after pushing.
> 
> You should make sure the tests are changed only for the tests specified for API 29 or below.

Thats very nice of you. :)
It took me a bit but I figured out how to find the test outputs on github :)
It seems the ones that are failing are tests that are not specified for any api version. Will those be executed on all api versions or only on the most recent one, which would be 30?

2020-10-21 15:49 UTC, lazylazyllama commented
The android tests seem to be working now.

2020-10-29 23:28 UTC, GaryQian approved these changes
LGTM! Thanks for getting the tests done, and I apologize for not getting to it last week. In any case, thank you for the contribution!

2020-10-30 00:28 UTC, merged