WIP: Smooth windows resizing on Windows
flutter/engine pull request #22279
Opened 2020-11-03 23:15 UTC by knopp

## Description

Fixes resize glitches on windows.

## Related Issues

https://github.com/flutter/flutter/issues/44136
https://github.com/flutter/flutter/issues/66475

## Tests

I added the following tests:

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [X] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [X] I signed the [CLA].
- [X] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [X] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [X] I updated/added relevant documentation.
- [X] All existing and new tests are passing.
- [X] I am willing to follow-up on review comments in a timely manner.

## Reviewer Checklist

- [ ] I have submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [X] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[contributor guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[CLA]: https://cla.developers.google.com/
[tree hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[engine presubmit flakes form]: https://forms.gle/Wc1VyFRYJjQTH6w5A

2021-01-13 20:49 UTC, iskakaushik requested changes

2021-01-13 20:49 UTC, iskakaushik commented on shell/platform/windows/flutter_windows_view.cc
> +#include <dwmapi.h>
order lexicographically.

2021-01-13 20:49 UTC, iskakaushik commented on shell/platform/windows/flutter_windows_engine.cc
> +      return 0;
can you add a comment on when this could happen? When can `host->view()` return null?

2021-01-13 20:49 UTC, iskakaushik commented on shell/platform/windows/flutter_windows_engine.cc
> +    auto host = static_cast<FlutterWindowsEngine*>(user_data);
Why call this `host` as opposed to `engine`?

2021-01-13 20:49 UTC, iskakaushik commented on shell/platform/windows/flutter_windows_view.h
> +  size_t pending_width_, pending_height_;
Call these `resize_target_width_` and `resize_target_height_`. Also expand the comment to write a note that these are only valid then `resize_pending_` is set to `true`.

2021-01-13 20:49 UTC, iskakaushik commented on shell/platform/windows/flutter_windows_view.h
> +  bool resize_waiting_;
nit: `resize_pending_`

2021-01-13 20:49 UTC, iskakaushik commented on shell/platform/windows/flutter_windows_view.h
> +  std::mutex resize_mutex_;
Expand the comment to say that `resize_pending_`, `resize_target_width_` and `resize_target_height_` are also guarded by this mutex.

2021-01-13 20:49 UTC, iskakaushik commented on shell/platform/windows/flutter_windows_view.h
> +  // target size during resize event
Capitalize the first word here and in the other comments.

2021-01-13 20:49 UTC, iskakaushik commented on shell/platform/windows/flutter_windows_view.cc
> +  if (pending_width_ == width && pending_height_ == height) {
Can you wrap this block with `if (resize_waiting_) {}`? That way its clear that `pending_width_` and `pending_height_` are only valid during resize.

2021-01-13 20:49 UTC, iskakaushik commented on shell/platform/windows/flutter_windows_view.cc
> +  auto res = surface_manager_->SwapBuffers();
`auto` -> `bool`. It isn't easy to infer what the type is.

2021-01-13 20:49 UTC, iskakaushik commented on shell/platform/windows/flutter_windows_view.cc
> +    DwmFlush();
We might want to log when `DwnFlush` returns non-success.

2021-01-27 12:18 UTC, MrBirb commented
@iskakaushik Should this be closed since yours was merged?

2021-02-08 19:37 UTC, closed without merging