[embedder] FlutterBackingStoreConfig allows special treatment of root-views
flutter/engine pull request #22642
Opened 2020-11-20 16:55 UTC by iskakaushik

2020-11-23 17:11 UTC, RichardJCai approved these changes

2020-11-23 22:44 UTC, chinmaygarde requested changes
With custom composition, there is no such thing as a root view/surface (I believe documentation even states that). I am not sure what use case there is for this in the public API?

2020-11-23 23:33 UTC, iskakaushik commented
@RichardJCai we have a stable ordering for the layers. We can safely assume that the first layer is indeed the root-layer. We do not need this PR.

2020-11-23 23:33 UTC, closed without merging

2020-11-24 16:30 UTC, RichardJCai commented
Hey @chinmaygarde, the reason we wanted this is because when creating a backing store for the first layer, we wanted to be able to re-use to fbos provided by FlutterSurfaceManager (to use current behaviour / prevent regressions). 

The `is_root_view` lets us know when CreateBackingStore is called if the layer is the first one or not. I think we still want to be able to know if the layer requesting the backing store is the first layer. Do you have any suggestions on how to do this or if this is even the right approach?