Implement delayed key event synthesis for Windows
flutter/engine pull request #23524
Opened 2021-01-08 01:51 UTC by gspencergoog

## Description

This changes the Windows text handling so that keyboard events are sent to the framework first for handling, and then passed to the text input plugin, so that the framework has a chance to handle keys before they get given to the text field.

This is complicated by the async nature of the interaction with the framework, since Windows wants a synchronous response. So, in this change, I always tell Windows that the event was handled, and if the framework (eventually) responds that it wasn't, then I synthesize a new event and send it with `SendEvent`.

I also added support for detecting "extended" keys, since that was missing, and converted the `OnKey` handlers in the API to return a `bool` to indicate whether or not they have handled the event.

## Related Issues

- https://github.com/flutter/flutter/issues/47156

## Tests

 - Added tests for key handling to make sure that it sends a new event when the framework doesn't handle it.

2021-01-10 19:12 UTC, clarkezone reviewed
This generally LGM both for the current Win32 backend as well as the impending UWP/CoreWindow impl.  One request would be to take a look at https://github.com/flutter/engine/pull/23573 and LMK if _you_ have any concerns with this working with CoreWindow.  I don't think there will be but would be good to have your ACK.

2021-01-12 21:49 UTC, dkwingsmt commented
The code looks fine, but can you add some unit tests for it? I see at least 3 cases we need to add:
- Handled/unhandled events
- Handled text events
- Extended bit

Especially considering I'm definitely touching this part in my keyboard PR.

2021-01-12 22:16 UTC, dkwingsmt requested changes
See comment above

2021-01-13 18:37 UTC, gspencergoog commented
OK, I'll add some more tests.

2021-01-20 01:43 UTC, gspencergoog commented
OK, @dkwingsmt I've added a bunch more testing of the event handling from the framework.  The test simulates the framework response, and tests for printable, non-printable, and modifier key events (since they have slightly different code paths in Windows).

2021-01-21 06:32 UTC, dkwingsmt commented on shell/platform/windows/key_event_handler.cc
> +uint64_t CalculateEventId(int scancode, int action, bool extended) {
Why use this complicated calculation instead of self-incrementing ID?

2021-01-21 08:12 UTC, dkwingsmt requested changes
Tests take some effort to understand, among other small change requests. Otherwise looking good.

2021-01-21 08:12 UTC, dkwingsmt commented on shell/platform/windows/win32_flutter_window_unittests.cc
> +      [&pending_events](UINT cInputs, LPINPUT pInputs, int cbSize) -> UINT {
Similarly we can move pending_events to `TestFlutterWindowsView` and leave out a `clearPendingEvent` method for clarity.

2021-01-21 08:12 UTC, dkwingsmt commented on shell/platform/windows/win32_flutter_window_unittests.cc
> +  EXPECT_CALL(
Can we use plain blocks (`{   }`) to wrap the two sub-tests so that `EXPECT_CALL` is more reliable?

2021-01-21 08:12 UTC, dkwingsmt commented on shell/platform/windows/win32_flutter_window_unittests.cc
> +// Tests key event propagation of modifier key down events.
Can you tell me, or point me to, why they should behave differently? Is it because `SendEvent` doesn't simulate `WM_CHAR` events for them?

2021-01-22 19:28 UTC, dkwingsmt commented on shell/platform/windows/key_event_handler.cc
> +        << "framework. Are responses being sent?" << std::endl;
Sorry, it's actually `FML_DCHECK`

2021-01-22 20:42 UTC, dkwingsmt commented on shell/platform/windows/key_event_handler.cc
> +uint64_t CalculateEventId(int scancode, int action, bool extended) {
Great explanation. Can you add it to the code?

2021-01-22 20:42 UTC, dkwingsmt approved these changes
LGTM except for 2 nits

2021-01-22 22:59 UTC, gspencergoog commented on shell/platform/windows/key_event_handler.cc
> +  FML_DCHECK(pending_events_.size() < kMaxPendingEvents)
Actually, I can't use this here because including FML is a layer violation.  I'm going to go back to the cerr output...

2021-01-23 02:14 UTC, merged