Send path+query from pushRoute in Android
flutter/engine pull request #23561
Opened 2021-01-09 07:52 UTC by sarbagyastha

## Description
Currently, android platform only sends URL path obtained from deeplink . This PR sets route as `path + query` instead of just path. 

## Related Issues

Fixes flutter/flutter#73637

## Tests

I have updated the test files.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [contributor guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [C++, Objective-C, Java style guides] for the engine.
- [x] I read the [tree hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation.
- [x] All existing and new tests are passing.
- [x] I am willing to follow-up on review comments in a timely manner.

## Reviewer Checklist

- [ ] I have submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

## Breaking Change

Did any tests fail when you ran them? Please read [handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change.

2021-01-09 09:20 UTC, sarbagyastha commented
/cc @chunhtai

2021-01-11 17:41 UTC, chunhtai commented
hi @sarbagyastha thanks for putting up the PR, cc @johnpryan This looks something we have missed, do we need to update the doc regarding this change?

2021-01-11 23:57 UTC, chunhtai requested changes
LGTM except the gitignore changes

2021-01-11 23:57 UTC, chunhtai commented on .gitignore
> +.cipd/
can you revert change to this file?

2021-01-12 00:33 UTC, sarbagyastha commented on .gitignore
> +.cipd/
@chunhtai Done.

2021-01-12 00:35 UTC, chunhtai approved these changes

2021-01-13 00:02 UTC, merged