Fix incorrectly inserting Float32List in the wrong location in encodable_value
flutter/engine pull request #26537
Opened 2021-06-02 13:11 UTC by fuzzybinary

This is to address an issue introduced in flutter/engine#26386 and part of the fix for flutter/flutter#72613

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.
- [ ] The reviewer has submitted any presubmit flakes in this PR using the [engine presubmit flakes form] before re-triggering the failure.

2021-06-02 13:13 UTC, fuzzybinary commented
@stuartmorgan you're probably the correct reviewer on this one.

2021-06-02 14:08 UTC, stuartmorgan requested changes
The fix looks good, but there should be a test added that would have caught this in the first place (per Flutter policy). Could you add a test to https://github.com/flutter/engine/blob/master/shell/platform/common/client_wrapper/encodable_value_unittests.cc that creates a value of each type and then checks that its `index` is the expected value?

2021-06-02 20:20 UTC, fuzzybinary commented
Added the tests @stuartmorgan let me know if that's what you had in mind.

2021-06-03 13:47 UTC, stuartmorgan requested changes
The test looks good modulo nits; that is indeed what I had in mind. This should be good to land once the minor changes are made. Thanks for the quick fix.

2021-06-03 13:47 UTC, stuartmorgan commented on shell/platform/common/client_wrapper/encodable_value_unittests.cc
> +class MockCustomValue {
s/Mock/Test/ since this isn't a mock of anything.

2021-06-03 13:47 UTC, stuartmorgan commented on shell/platform/common/client_wrapper/encodable_value_unittests.cc
> +  EXPECT_EQ(EncodableValue(std::vector<uint8_t>{0, 1}).index(), 6u);
Nit: you could simplify all of the collections; there's no reason they need to contain any values. Having a bunch of extra setup just obfuscates the purpose of the test IMO.

2021-06-03 14:24 UTC, fuzzybinary commented
Fixed nits. Thanks for helping me get this through!

2021-06-03 15:43 UTC, stuartmorgan approved these changes
LGTM

2021-06-03 16:09 UTC, merged