Add more assert in ios a11y scrollable calculation
flutter/engine pull request #28137
Opened 2021-08-17 19:37 UTC by chunhtai

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-08-17 19:57 UTC, Hixie commented
test-exempt: no semantic change (adds asserts only)

2021-08-18 17:20 UTC, gaaclarke requested changes

2021-08-18 17:20 UTC, gaaclarke commented on shell/platform/darwin/ios/framework/Source/SemanticsObject.mm
> +            @"The global rect must be finite %@", NSStringFromCGRect(resultInScreenCoordinates));
You should make these separate assert calls.  The way this is written, if one of them fails, you won't know which one failed.

2021-08-18 17:20 UTC, gaaclarke commented on shell/platform/darwin/ios/framework/Source/SemanticsObject.mm
> +            @"The global rect must be finite %@", NSStringFromCGRect(resultInScreenCoordinates));
Also split out a function `isRealNumber(x) => isfinite(x) && !isnan(x)`

2021-08-24 20:27 UTC, closed without merging