Use separate io_manager when spawn engine
flutter/engine pull request #28220
Opened 2021-08-20 12:07 UTC by zsunkun

Each Engine should use its own io_manager when spawn new engine. The current situation is that when a new Engine is spawned from an old Engine, the new Engine will use the io_manager of the old Engine. the new Engine will be crash when the old Engine is destroyed.
For example:
![device-2021-08-20-195426](https://user-images.githubusercontent.com/5997059/130229456-ecb0f24e-d879-4920-96a2-f0e06f0b1827.png)
In this case, two engines are used to display GIF images on the same page, when I remove the top flutterView and destroy the engine, the bottomEngine will continue to decode pictures, but it will be crash because io_manager is null 
![image](https://user-images.githubusercontent.com/5997059/130229800-1f778a0d-7895-40d2-8b8d-98049afcfcbe.png)

In addition, when I modified the code, I found that ImageDeocoder also had the same problem. In other words, there will be similar crash in certain situations ,please take a look

2021-08-23 16:54 UTC, eggfly commented
@gaaclargar @blasten @iskakaushis A PR of my teammate, please take a review~ thanks

2021-08-23 16:58 UTC, gaaclarke requested changes
Hi zsunkun, good detective work.  This PR is going to need tests.  I recommend writing tests that recreate the crash (without your change).

2021-09-02 20:23 UTC, chinmaygarde commented
Agreed, the test to add would go in the `shell_unittests` harness. Perhaps a variant of `TEST_F(ShellTest, Spawn)`?

2021-09-02 20:23 UTC, chinmaygarde commented
Agreed, the test to add would go in the `shell_unittests` harness. Perhaps a variant of `TEST_F(ShellTest, Spawn)`?

2021-09-02 20:23 UTC, chinmaygarde commented
Agreed, the test to add would go in the `shell_unittests` harness. Perhaps a variant of `TEST_F(ShellTest, Spawn)`?

2021-09-09 20:24 UTC, chinmaygarde commented
Any updates?

2021-09-16 20:19 UTC, chinmaygarde commented
Closing this as stale. Please re-open once this is good for another review. Thanks.

2021-09-16 20:19 UTC, closed without merging

2021-11-24 15:25 UTC, eggfly commented
This PR takes place of it https://github.com/flutter/engine/pull/29915