Reset viewport_metrics when spawn new Engine
flutter/engine pull request #28221
Opened 2021-08-20 12:31 UTC by zsunkun

physical_width and physical_height should be reset to 0 when spawn new Engine. Otherwise, flutter will use the wrong width and height for layout, and if the developer uses SizeChangedLayoutNotifier, the wrong width and height will be obtained before onSizeChanged is called.

2021-08-21 14:51 UTC, knopp requested changes

2021-08-21 14:51 UTC, knopp commented on runtime/runtime_controller.cc
> +  result->platform_data_.viewport_metrics.ResetForSpawn();
Is it really necessary to have a special method for this? Shouldn't this work just as well?
```cpp
result->platform_data_.viewport_metrics = ViewportMetrics();
```

2021-09-02 20:32 UTC, chinmaygarde commented
cc @gaaclarke

2021-09-02 21:30 UTC, gaaclarke requested changes
Please add a test.  Check out existing Spawn tests, you might be able to just throw in an extra assert.

2021-09-16 20:11 UTC, chinmaygarde commented
Any updates on a test per Aarons suggestion?

2021-11-22 07:20 UTC, ColdPaleLight commented
Closing this PR, as the colleague of the author , @eggfly is taking over it at https://github.com/flutter/engine/pull/29876 .

2021-11-22 07:20 UTC, closed without merging