WIP: Rename image/decoding symbols to follow Chromium style
flutter/engine pull request #28740
Opened 2021-09-20 23:22 UTC by bdero

2021-09-23 18:33 UTC, dnfield commented on lib/ui/painting/image_descriptor.h
> +///         `InitstantiateCodec` a lightweight operation.
Find and replace mistake?

2021-09-23 18:36 UTC, dnfield requested changes
Per https://google.github.io/styleguide/cppguide.html#Function_Names, accessors/mutators for object fields can be named like fields. We do this elsewhere. I think these are fine.

The `initEncoded` method is exposed to Dart with that casing, and it's ab it confusing to mix it - I think we should leave that one as well, or change _all_ of them for all the native peers instead of just this one.

2021-09-23 18:36 UTC, dnfield commented
(It's telling, in particular, that many of these methods are defined inline in the header because they're just setting/getting a private ivar)

2021-09-24 19:54 UTC, bdero commented
> Per https://google.github.io/styleguide/cppguide.html#Function_Names, accessors/mutators for object fields can be named like fields. We do this elsewhere. I think these are fine.

Ah, I had a suspicion I was missing something here.

> The initEncoded method is exposed to Dart with that casing, and it's ab it confusing to mix it - I think we should leave that one as well, or change all of them for all the native peers instead of just this one.

Agreed. At first I also just renamed all of the stuff bound to Dart, but realized that just shifts the style inconsistency to the otherwise pristine Dart that users will encounter way more often in practice and reverted it.

This resolved some of my lingering style confusion. Thanks!

2021-09-24 19:54 UTC, closed without merging