maybeGetInitialRouteFromIntent: check if URI data getPath() is null
flutter/engine pull request #29766
Opened 2021-11-16 10:52 UTC by icota

[getPath](https://developer.android.com/reference/android/net/Uri?hl=da#getPath()) returns a null in case of non-hierachical URIs like `mailto`

This PR avoids the app crashing with:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
```

Fixes https://github.com/flutter/flutter/issues/75261

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-11-16 15:52 UTC, MrBirb commented on shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java
>          String fullRoute = data.getPath();
Why not move this outside the if and use it in the if statement? Instead of calling getPath two times.

2021-11-18 21:13 UTC, chinmaygarde commented
Looks good to me but I don't know how to test this. cc @blasten for thoughts.

2021-11-18 21:13 UTC, chinmaygarde approved these changes

2021-11-18 21:43 UTC, blasten commented on shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java
> +      if (data != null) {
`FlutterActivityAndFragmentDelegateTest.java` has a few examples about how to test this.

2021-11-18 21:43 UTC, blasten requested changes
needs test

2021-12-02 21:09 UTC, chinmaygarde commented
cc @blasten. The test has been added per the suggestion. Please take another look.

2021-12-03 01:49 UTC, blasten commented on shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java
> +      if (data != null) {
nit:  This would be more readable: 

```java
if (data == null) {
  return null;
}
```

2021-12-03 01:50 UTC, blasten approved these changes
LGTM

2021-12-09 21:02 UTC, chinmaygarde commented
The linter failure is real. @icota Can you patch that please so we can land this?

2021-12-11 11:17 UTC, icota commented
Thanks for letting me know @chinmaygarde. Fixed in https://github.com/flutter/engine/pull/29766/commits/8f9e9edd1a96c32bdbde2e90252ac12cf2601634

2021-12-16 21:09 UTC, merged