Add copy assignment operator for 'EmbeddedViewParams'
flutter/engine pull request #30094
Opened 2021-12-03 01:32 UTC by jmagman

Fixes https://github.com/flutter/flutter/issues/94586

Tested this locally with clang 13, will be validated on the Xcode 13 migration with the ` -Wdeprecated-copy` warning.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-12-03 18:40 UTC, cyanglaz approved these changes
LGTM

2021-12-03 22:13 UTC, dnfield requested changes
Add FML_DISALLOW_COPY_AND_ASSIGN to the class.

2021-12-04 01:56 UTC, chinmaygarde commented
@dnfield Curious why this can't be copy, move, and, assignable? There aren't really any problematic members. Though, looking at the uses of this within the engine, there isn't really any reason this must be copy/move/assignable. Just that changing it now will require updating a lot of TUs.

2021-12-04 04:58 UTC, dnfield commented
IME it gets confusing when a class is copyable - eventually it gets used in something that should be moved rather than copied, or it ends up including a member that's expensive to copy rather than move, and whoever added that code doesn't realize that the class is copied somewhere in the codebase. 

I guess I might have misunderstood though - is this class actually copied somewhere and we're saying the default copy ctor is fine?

2021-12-04 20:26 UTC, chinmaygarde approved these changes
> I guess I might have misunderstood though - is this class actually copied somewhere and we're saying the default copy ctor is fine?

@dnfield: Yes, it is copied today ([here for instance](https://github.com/flutter/engine/blob/0add38502ed4ef48c152923e6f8b3323dd073029/shell/platform/fuchsia/flutter/tests/gfx_external_view_embedder_unittests.cc#L436)) and the default copy ctor is fine. We will have to rework a whole bunch of code if the copy and assigns were to be deleted.

Just deleting the explicit copy constructor is the the ideal way ahead for the following reasons:
* It is straightforward.
* It unblocks @jmagman s work immediately on a high priority task.
* It is functionally identical to the current behavior.
* It doesn't violate the rules of 3/5.
* It adheres to the style guide.

An argument could be made that this shouldn't have been copyable in the first place, but changing this class now distracts from @jmagman 's primary objective and is of dubious value anyway since it is not particularly expensive to copy.

2021-12-04 20:37 UTC, dnfield approved these changes

2021-12-04 20:38 UTC, dnfield commented
Sgtm. I thought this was unused

2021-12-06 17:34 UTC, merged