Check string size before Win32 MultiByte <-> WideChar conversions
flutter/engine pull request #30111
Opened 2021-12-03 15:46 UTC by tgucio

This PR adds string size checks after .resize() before calling WideCharToMultiByte / MultiByteToWideChar.

This is to avoid buffer overruns should resize() call fail (e.g. alloc error or too long a string length). As per C++ standard: "Strong guarantee: if an exception is thrown, there are no changes in the string".

According to Win32 API docs ([WideCharToMultiByte](https://docs.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-widechartomultibyte), [MultiByteToWideChar](https://docs.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-multibytetowidechar)) it's the caller responsibility to make sure the buffers are correctly allocated:

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

2021-12-06 18:16 UTC, chinmaygarde commented
The engine is built with exceptions disabled. Any attempts at an exception being thrown should terminate the process. OTOH, if an exception were to be thrown, this patch doesn't add an exception handler either. So, I am not sure if this does anything useful. Is there an issue you are trying to work around? Perhaps add that to `string_conversions_unittests.cc` and start from there?

2021-12-06 18:16 UTC, chinmaygarde requested changes
For the previous comment.

2021-12-12 14:38 UTC, tgucio commented
Thanks for taking a look - I guess I should have provided a bit of background.

This came up in a review when chasing some Win32 app crashes, some if which were attributed to clipboard operations. I noted in multiple calls to WideCharToMultiByte and MultiByteToWideChar it was possible to pass insufficient buffer that could be overrun. There's also a separate PR for the Win32 template etc: https://github.com/flutter/flutter/pull/94608.

After re-reading what the C++ standard says, I agree this is better handled with proper try / catch so I'll update the PR. What are the exact compiler flags in the engine build (couldn't find that from the PR check build logs) - do they turn all try/catch clauses into no ops and terminate the app immediately where the std C++ lib would throw an exception?

I experimented by adding a little plugin with native Windows code to handle clipboard copy with Utf16FromUtf8() changed to resize the string to an invalid value:
```
  HANDLE stdOut = GetStdHandle(STD_OUTPUT_HANDLE);
  DWORD written = 0;
  const char *message1 = "about to do something ugly utf16\n";
  WriteConsoleA(stdOut, message1, (DWORD) strlen(message1), &written, NULL);

  std::wstring utf16_string;
  try {
    utf16_string.resize(utf16_string.max_size() + 1);
  } catch (...) {
    const char *message3 = "exit!\n";
    WriteConsoleA(stdOut, message3, (DWORD) strlen(message3), &written, NULL);
    return std::wstring();
  }

  const char *message2 = "hey ho\n";
  WriteConsoleA(stdOut, message2, (DWORD) strlen(message2), &written, NULL);
```

This is handled well:
```
C:\Users\tgucio\Desktop\wrk\flutter\test\build\windows\runner\Debug>about to do something ugly utf16
exit!
about to do something ugly utf16
exit!
about to do something ugly utf16
exit!
```

By default plugin native code is compiled with /EHsc in both debug and release:

```
[        ]   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\CL.exe /c /IC:\Users\tgucio\Desktop\wrk\flutter\test\windows\flutter\ephemeral
/IC:\Users\tgucio\Desktop\wrk\flutter\test\windows\flutter\ephemeral\cpp_client_wrapper\include /Zi /nologo /W4 /WX /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D _HAS_EXCEPTIONS=0 /D _DEBUG /D FLUTTER_PLUGIN_IMPL /D UNICODE /D _UNICODE /D      
"CMAKE_INTDIR=\"Debug\"" /D clipboard_plugin_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"clipboard_plugin.dir\Debug\\" /Fd"clipboard_plugin.dir\Debug\vc142.pdb"   
/external:W4 /Gd /TP /wd4100 /errorReport:queue C:\Users\tgucio\Desktop\wrk\flutter\test\windows\flutter\ephemeral\.plugin_symlinks\clipboard\windows\clipboard_plugin.cpp
```

```
[   +2 ms]   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\CL.exe /c /IC:\Users\tgucio\Desktop\wrk\flutter\test\windows\flutter\ephemeral
/IC:\Users\tgucio\Desktop\wrk\flutter\test\windows\flutter\ephemeral\cpp_client_wrapper\include /nologo /W4 /WX /diagnostics:column /O2 /Ob2 /D WIN32 /D _WINDOWS /D NDEBUG /D _HAS_EXCEPTIONS=0 /D FLUTTER_PLUGIN_IMPL /D UNICODE /D _UNICODE /D
"CMAKE_INTDIR=\"Release\"" /D clipboard_plugin_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /std:c++17 /Fo"clipboard_plugin.dir\Release\\" /Fd"clipboard_plugin.dir\Release\vc142.pdb"    
/external:W4 /Gd /TP /wd4100 /errorReport:queue C:\Users\tgucio\Desktop\wrk\flutter\test\windows\flutter\ephemeral\.plugin_symlinks\clipboard\windows\clipboard_plugin.cpp
```

2021-12-12 15:13 UTC, tgucio commented
Hah, ok, the build check helped to clarify this:

```
ninja -t msvc -e environment.x64 -- C:\b\s\w\ir\cache\goma\client/gomacc.exe ../../buildtools/windows-x64/clang/bin/clang-cl.exe  /nologo /showIncludes @obj/flutter/shell/platform/windows/string_conversion.string_conversion.obj.rsp /c ../../flutter/shell/platform/windows/string_conversion.cc /Foobj/flutter/shell/platform/windows/string_conversion.string_conversion.obj /Fdobj/flutter/shell/platform/windows/string_conversion_cc.pdb
../../flutter/shell/platform/windows/string_conversion.cc(22,3): error: cannot use 'try' with exceptions disabled
  try {
  ^
../../flutter/shell/platform/windows/string_conversion.cc(48,3): error: cannot use 'try' with exceptions disabled
  try {
  ^
2 errors generated.
```

This would mean then we can't handle the exception and unless with exceptions disabled the std C++ lib does nothing on resize() error (as opposed to terminating the app immediately), the string size check doesn't do much either.

As this method is used for clipboard operations, my concern was what would happen on alloc error (e.g. when the clipboard contains some erroneous / absurdly large amounts of data).

2021-12-12 22:39 UTC, chinmaygarde commented
> my concern was what would happen on alloc error.

The process would be terminated. If the data is erroneous, validation and correction must happen before it is put into std container. If it's too large for the container, I suppose another container that allows for exception-less allocations would have to be used. Either way, this simple utility doesn't handle these cases.

2022-02-14 13:46 UTC, tgucio commented
Closing as Utf8/16 conversion has moved to FML.

2022-02-14 13:46 UTC, closed without merging