Add attributes benchmarking and a saveLayer benchmark to DisplayList benchmarks
flutter/engine pull request #30964
Opened 2022-01-21 04:04 UTC by gw280

This adds a new saveLayer benchmark, and also adds the necessary changes to the harness to support benchmarking with different attributes.

The attributes are reported via the `benchmark` library's "counters" API - we report 1 if an attribute is enabled, and 0 if it isn't. Only attributes supported by the specific rasterop being benchmarked are reported.

For now, the attributes being benchmarked are:

* Hairline vs non-hairline stroke widths
* Stroked vs filled styles
* Anti-aliased vs non-anti-aliased

It should be relatively easy to add new attributes in the future.

2022-01-21 23:04 UTC, flar requested changes
Looks good except for drawColor in the saveLayers. That's a problematic corner case that I'm not sure we ever encounter in practice.

2022-01-21 23:04 UTC, flar commented on display_list/display_list_benchmarks.cc
> +
It looks like you benchmark these with the empty attributes so that should cover it.

2022-01-21 23:04 UTC, flar commented on display_list/display_list_benchmarks.cc
> +    paint.setStyle(SkPaint::kStrokeAndFill_Style);
Flutter doesn't have strokeAndFill, but it can't hurt to test it anyway as DL will accept that style.

2022-01-21 23:49 UTC, gw280 commented on display_list/display_list_benchmarks.cc
> +
Yes, everything should be benchmarked with empty attributes as well as any specialised ones

2022-01-24 20:44 UTC, gw280 commented on display_list/display_list_benchmarks.cc
> +    for (size_t j = 0; j < save_depth; j++) {
Changed it to two overlapping rectangles for every saveLayer.

2022-01-24 21:11 UTC, flar approved these changes
LGTM

2022-01-24 21:36 UTC, merged