Add clang-analyzer-* and clang-diagnostic-* to .clang-tidy
flutter/engine pull request #31291
Opened 2022-02-06 22:36 UTC by zanderso

The `CREATE_NATIVE_ENTRY()` pattern used in unit tests results in a lot of `clang-analyzer-core.StackAddressEscape` warnings due to the closures it gets passed retaining references to local variables. One way to resolve the warnings would be to declare all of those locals as `static`, however since the tests that use `CREATE_NATIVE_ENTRY()` are constructed to avoid the possibility of the callback getting called after the lifetime of the locals, that doesn't really seem like an improvement. Instead, this PR turns off checking for `clang-analyzer-core.StackAddressEscape` in the files where `CREATE_NATIVE_ENTRY()` and similar patterns are used.

This PR also ignores some warnings flagged due to `rapidjson`. We should find another json parsing solution, as suggested in https://github.com/flutter/flutter/issues/97680.

Related https://github.com/flutter/flutter/issues/93576

2022-02-08 06:25 UTC, bdero approved these changes
LGTM. The blinkenlights on https://github.com/flutter/engine/pull/31098 will be extreme. 😅

2022-02-08 19:25 UTC, jmagman requested changes
With this config file, no issues found with `./ci/lint.sh --lint-all --variant ios_debug`.  However  with `--variant host_debug` I see 
```
/Users/m/Projects/engine/src/flutter/fml/synchronization/waitable_event_unittest.cc:34:57: error: Function 'rand' is obsolete because it implements a poor random number generator.  Use 'arc4random' instead [clang-analyzer-security.insecureAPI.rand,-warnings-as-errors]
      TimeDelta::FromMilliseconds(static_cast<unsigned>(rand()) % 20u);
                                                        ^~~~
/Users/m/Projects/engine/src/flutter/fml/synchronization/waitable_event_unittest.cc:34:57: note: Function 'rand' is obsolete because it implements a poor random number generator.  Use 'arc4random' instead
      TimeDelta::FromMilliseconds(static_cast<unsigned>(rand()) % 20u);
                                                        ^~~~
/Users/m/Projects/engine/src/flutter/fml/synchronization/waitable_event_unittest.cc:76:13: error: Function 'rand' is obsolete because it implements a poor random number generator.  Use 'arc4random' instead [clang-analyzer-security.insecureAPI.rand,-warnings-as-errors]
        if (rand() % 2 == 0) {
            ^~~~
/Users/m/Projects/engine/src/flutter/fml/synchronization/waitable_event_unittest.cc:76:13: note: Function 'rand' is obsolete because it implements a poor random number generator.  Use 'arc4random' instead
        if (rand() % 2 == 0) {
            ^~~~
/Users/m/Projects/engine/src/flutter/fml/synchronization/waitable_event_unittest.cc:161:15: error: Function 'rand' is obsolete because it implements a poor random number generator.  Use 'arc4random' instead [clang-analyzer-security.insecureAPI.rand,-warnings-as-errors]
          if (rand() % 2 == 0) {
              ^~~~
/Users/m/Projects/engine/src/flutter/fml/synchronization/waitable_event_unittest.cc:161:15: note: Function 'rand' is obsolete because it implements a poor random number generator.  Use 'arc4random' instead
          if (rand() % 2 == 0) {
```
Not sure why the `impeller` headers aren't found:
```
/Users/m/Projects/engine/src/out/host_debug/../../flutter/impeller/entity/content_context.h:12:10: error: 'flutter/impeller/entity/gradient_fill.frag.h' file not found [clang-diagnostic-error]
#include "flutter/impeller/entity/gradient_fill.frag.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Since that linter runs during the pre-push githooks I think those errors need to be fixed before this can merge, or pushes from Mac development machines will be blocked.
https://github.com/flutter/engine/blob/6f99a713abe11a4d4a5bbf0cadabbea86cbe2374/tools/githooks/lib/src/pre_push_command.dart#L40-L46

2022-02-08 20:38 UTC, jmagman commented
Here's the full output:
[lint-output.txt](https://github.com/flutter/engine/files/8027312/lint-output.txt)

And here are the error (not warning) counts:
```
  30 clang-analyzer-core.StackAddressEscape
   1 clang-analyzer-cplusplus.NewDeleteLeaks
   1 clang-analyzer-optin.osx.cocoa.localizability.NonLocalizedStringChecker
   3 clang-analyzer-security.insecureAPI.rand
   1 clang-analyzer-security.insecureAPI.strcpy
```

2022-02-08 21:50 UTC, jmagman commented
https://github.com/flutter/engine/pull/31333 fixes macOS `host_debug` except the 30 `clang-analyzer-core.StackAddressEscape` errors.

2022-02-08 21:54 UTC, jmagman commented
> Our Objective-C code has a lot of inconsistencies around nullability.

I didn't see any nullability errors running the linter on top of this PR, which ones were you seeing?

2022-02-08 22:00 UTC, zanderso commented
> > Our Objective-C code has a lot of inconsistencies around nullability.
> 
> I didn't see any nullability errors running the linter on top of this PR, which ones were you seeing?

The PR silences them in the `.clang-tidy` file.

2022-02-09 16:15 UTC, zanderso commented
Thanks, Jenn! I think I've addressed the host_debug issues on macOS.

2022-02-09 20:21 UTC, jmagman approved these changes
> The PR silences them in the `.clang-tidy` file.

Oh right, missed the `-`.

> I think I've addressed the host_debug issues on macOS.

Tested locally, LGTM, thanks @zanderso!

2022-02-09 20:26 UTC, merged