Reland "Add a way to raster cache the children of a Layer (#32370)"
flutter/engine pull request #32378
Opened 2022-04-01 09:09 UTC by ColdPaleLight

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

2022-04-01 23:53 UTC, flar requested changes
This looks good, but I'd like to see a change in the naming of the child bounds. Perhaps "child_paint_bounds()" would be simple enough on its own because that is exactly what it is.

Also, the tests could be more relevant to what the layers are doing.

2022-04-01 23:56 UTC, flar commented on flow/layers/container_layer_unittests.cc
> +}
Perhaps every layer could have a test like this. I believe we have a unittests.cc for each layer type. The ones that don't modify the child bounds would have both paint_bounds() and child_paint_bounds() EQ the same rect. The ones that do modify the child bounds would use different rects to compare.

Layers I can think of off the top of my head that might have different bounds would be BackdropFilter, Clip<Shape>Layer, ImageFilterLayer - there may be more.

2022-04-02 07:16 UTC, flar commented on flow/layers/container_layer.h
> +  const SkRect& origin_child_paint_bounds() const {
In the review comment I think I convinced myself that "child_paint_bounds()" is a good name choice for this field.

2022-04-02 13:30 UTC, ColdPaleLight commented on flow/layers/container_layer.h
> +  const SkRect& origin_child_paint_bounds() const {
done, rename to "child_paint_bounds()".

2022-04-02 13:41 UTC, ColdPaleLight commented on flow/layers/container_layer_unittests.cc
> +}
Good idea. In the unittests of container_layer and its 10 subclasses, I added codes to verify `child_paint_bounds`.

2022-04-06 11:12 UTC, flar commented on flow/layers/container_layer_unittests.cc
> +}
That was a *lot* of work. Thank you!

2022-04-06 11:13 UTC, flar approved these changes
I didn't review every single additional test of child_paint_bounds(), but the implementation looked right and they pass, so I'm going to accept all of that on faith.

LGTM

2022-04-06 11:16 UTC, merged