[Linux] read settings from XDG desktop portal if available
flutter/engine pull request #33100
Opened 2022-05-04 11:56 UTC by jpnurmi

This PR introduces `FlSettingsPortal` that implements the `FlSettings` interface for the XDG desktop portal. On older systems where the portal is not available, the current `GSettings`-based implementation is used. This fixes the issue that Flutter would not detect dark system themes in many desktop environments such as GNOME 42 or later, and KDE.

Fixes: flutter/flutter#101438

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

2022-05-04 11:58 UTC, jpnurmi commented
# Kubuntu 22.04
| Light | Dark |
|---|---|
| ![Screenshot from 2022-05-04 10-45-37](https://user-images.githubusercontent.com/140617/166676794-16e0360d-4cb7-462d-a766-2497dca77709.png) | ![Screenshot from 2022-05-04 10-45-07](https://user-images.githubusercontent.com/140617/166676799-937dc346-9e56-4e05-a643-661bede8ae9e.png) |

2022-05-04 21:14 UTC, robert-ancell commented on shell/platform/linux/fl_settings_portal.cc
> +static const gchar* fl_settings_portal_format_key(const FlSetting* setting) {
Remove the const? This is an allocated string.

2022-05-04 21:15 UTC, robert-ancell commented on shell/platform/linux/fl_settings_portal.cc
> +static const gchar* fl_settings_portal_format_key(const FlSetting* setting) {
Having the `fl_settings_portal_` prefix makes this look like a method on FlSettingsPortal. I suggest renaming it to `format_key` (and the same for other static functions in this file).

2022-05-04 21:19 UTC, robert-ancell commented on shell/platform/linux/fl_settings_portal.cc
> +#define FL_SETTINGS_PORTAL_GET_PRIVATE(portal) \
This code seems unused.

2022-05-04 21:20 UTC, robert-ancell commented on shell/platform/linux/fl_settings_portal.cc
> +static gboolean settings_portal_read(GDBusProxy* proxy,
The (undocumented) convention in the other files is to move the static functions to the top of the file.

2022-05-04 21:22 UTC, robert-ancell commented on shell/platform/linux/fl_settings_portal.h
> +FlSettingsPortal* fl_settings_portal_new(GVariantDict* values);
Since values is just for testing might be clearer to have `fl_settings_portal_new` and `fl_settings_portal_new_with_test_values`.

2022-05-04 21:23 UTC, robert-ancell commented on shell/platform/linux/fl_settings_portal.h
> +gboolean fl_settings_portal_start(FlSettingsPortal* portal);
Probably a good idea to set a `GError` on failure, so it's easier to debug in a higher level.

2022-05-04 21:23 UTC, robert-ancell requested changes
Great work, thanks!

2022-05-09 21:13 UTC, robert-ancell approved these changes
LGTM

2022-05-12 20:09 UTC, chinmaygarde commented
Can we land this?

2022-05-12 20:10 UTC, chinmaygarde approved these changes

2022-05-12 21:06 UTC, merged