Disable dart:io::exit(). It now throws UnsupportedError instead.
flutter/engine pull request #33400
Opened 2022-05-16 20:27 UTC by zanderso

2022-05-16 21:50 UTC, chinmaygarde approved these changes

2022-05-16 22:08 UTC, dnfield requested changes
I don't think this works.

If you call this in a Flutter application today, the process exits (maybe with a crash becuse you picked a bad time to exit for some other thread).

If you call this in a Flutter application with this patch, the process will almost certainly not exit - you'll get an exception logged in the unhandled exception handler and the process will continue along merrily.

That seems like it could cause some pretty unexpected effects, putting an application that already was in a bad state into a worse one but without forcing it to exit.

We'd also still have the problem of plugins or other platform specific code causing the process to exit/abort unexpectedly.

2022-05-16 22:11 UTC, dnfield commented
We also have at least one spot in Flutter documentation where we currently tell users to call exit: https://api.flutter.dev/flutter/flutter_test/benchmarkWidgets.html

2022-05-16 22:13 UTC, dnfield commented
I'm probably forgetting something we discussed at this morning's triage, but at the least we should update that documentation and document more thoroughly here why we think these problems are better than the ones we have :)

2022-05-16 22:34 UTC, jtmcdole commented
This is going to break some features of interal projects. Is there a work around to this?

2022-05-16 22:36 UTC, mraleph commented
If you don't think there is any way to cleanly shut the engine down using some combination of `atexit` callbacks, then you could consider calling `_exit` (`_Exit` on Mac OS X / iOS) - this should bypass any cleanup and avoid crashes like https://github.com/flutter/flutter/issues/103587

2022-05-16 22:57 UTC, zanderso commented
> If you call this in a Flutter application with this patch, the process will almost certainly not exit - you'll get an exception logged in the unhandled exception handler and the process will continue along merrily.

Yeah, that would be the intended behavior `dart:io::exit()` after this PR.

> That seems like it could cause some pretty unexpected effects, putting an application that already was in a bad state into a worse one but without forcing it to exit.

Right, the idea is that users shouldn't be calling `dart::io:exit()`. After some discussions over chat, I think it is the case that we should have an alternative, though, so I'm going to move this PR to WIP while I look into that.

> We'd also still have the problem of plugins or other platform specific code causing the process to exit/abort unexpectedly.

This PR isn't intended to be a solution to that problem.

2022-05-17 07:04 UTC, dnfield commented
@mraleph won't `_exit` attempt to close file handles, which may take some amount of time and still allow for such crashes?

2022-05-17 08:41 UTC, mraleph commented
@dnfield IIUC the crashes that have been reported so far are due to various statically initialised data structures (like mutexes) being destroyed. Using `_exit` would avoid this. It is true that you can hit some other problems with file descriptors, by closing them while some threads are reading/writing but I'd recon the probability of that is rather low.

2022-05-19 20:32 UTC, chinmaygarde commented
I am not sure if `_exit` counts as a private API on iOS. Apps may get rejected on account of us invoking it. Let's make sure it is public before adding invocations to it.

2022-05-20 07:28 UTC, mraleph commented
@chinmaygarde It has a man page, I doubt it's non-public. 

https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/_Exit.3.html

2022-07-21 20:26 UTC, chinmaygarde commented
From Triage: @zanderso is going to write a doc for this. Closing if for now.

2022-07-21 20:26 UTC, closed without merging