Create benchmarks for DisplayListBuilder
flutter/engine pull request #34910
Opened 2022-07-26 12:47 UTC by ColdPaleLight

benchmarks for display list builder/display list

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

2022-07-26 20:22 UTC, flar commented
I think we need to tailor how we apply all of the bits and pieces. Running all variants of drawRect/drawAtlas/etc. is probably fine, but on each build out we run all of the transform, all of the clip, and all of the saveLayer calls together. Plus, we have pretty much all of the attributes set every which way. I think a good reason that the mapRect call was having such an impact is that we probably left the DL with a nasty perspective matrix for all the rest of the ops to be built on, but perspective is such a corner case in practice.

One technique might be to break out the big array into smaller groups and then we can mix and match then in more controlled ways:
- One vector for all of the rendering ops
- One vector for transform variations
- One vector for clip variations
- Perhaps different versions of the transform/clip/attribute/save vectors for benchmarking just a few options vs the full testing done for the correctness testing.
- "allGroups" (maybe with a better name) would then be a concatenation of the "every variation" vectors in each category.
- benchmarking would mainly work with "allRenderingOps" vector and then have a few variations of the other state to combine that vector with

We then could have (the following is a full list, but we might want to start with a subset, see below):
- time for unmodified render ops construction
- time for render ops under (?translate?), scale, (?rotate?), perspective matrices
- time for render ops under clipRect/(?RR/Path?)
- with and without saveLayer/restore
- perhaps with non-Layer-save/restore sprinkled about ridiculously (we may want to optimize those out eventually)
- time for render ops with a couple of stroke variations (PathEffect very rarely used, not worth benchmarking?)
- time for render ops with an ImageFilter (most typically a Blur, others are rarely used)
- possibly combine some of those latter categories with a simple scale, but not a whole suite of transform types
- (any other attributes that will complicate construction?)

For starters I'd like to see a simple small number of benchmarks with the most common variations:
- identity (most ui.Picture objects don't have a DPI scale built in)
- scale/translate (most LayerTrees have a DPI scale at the root level and then a translate here and there for layout)
- (maybe perspective for shock value)
- clipRect (I think clipRRect is also used in a few cases, but probably doesn't add much time)
- (bunch of ops) then `saveLayer` then (bunch of ops) then restore
- saveLayer suite as above, but with blur image filter on saveLayer

I'm not sure what to do about attributes for now as I do want to know how long they take, but I don't want to have lots of random settings through most of the benchmarks. The reason they should be benchmarked is that they can do deep copies of complex attributes and it would be good to know how much that costs us in the long run, but I don't think that is urgent at this time, something we can add over time.

2022-07-27 09:47 UTC, ColdPaleLight commented
@flar 
I tweak the code as you suggested and updated the benchmarks data on the top.

2022-07-27 21:52 UTC, flar commented
It looks like the new code can compute DL+bounds (the most common case by far) very close to the same speed as the old 2-pass code. I was hoping it might save some time, and it does with some of the more complex cases like having a layer+image filter. But, one thing it makes much faster is computing the RTree after the fact.

Also, now that we compute bounds during construction we can do things like enhance the peephole optimizations by detecting non-overlapping content better.

![DL Cost of construction + bounds](https://user-images.githubusercontent.com/50503328/181379041-b56e8033-b43a-4ac9-b056-f94dc102c71c.png)

2022-07-27 22:04 UTC, flar commented
Another thing to consider is that this didn't help with the case of constructing a DL and then computing an RTree without also computing Bounds. You didn't collect benchmark data for that case, but I inferred it using "result2 - result1 + result0" and came up with the following graph.

![DL Construct + RTree](https://user-images.githubusercontent.com/50503328/181380313-01cafe8f-5775-449f-8aa4-7c4d5e8eea63.png)

The only target we currently have for computing an RTree will be when DL gets used to collect pieces of scenes that are in front of, behind, and between external embedded platform views. In those cases, I don't think we would compute the bounds, just the RTree.

But, future work might benefit from the fact that the trifecta of "construct + bounds + rtree" is faster now if we add fast-rtree-culling to the dispatch of a DisplayList.

2022-07-27 22:08 UTC, flar commented
Those last 2 comments are really about the benefit of the work done in https://github.com/flutter/engine/pull/34365

This PR, which simply adds the benchmark will be important regardless of that other work, so I'll review it with intent to land it as work progresses on the subsequent developments of DL/bounds/RTree...

2022-07-28 23:00 UTC, flar requested changes

2022-07-29 07:33 UTC, ColdPaleLight commented on display_list/display_list_test_utils.cc
> +std::vector<DisplayListInvocationGroup> allRenderingOps =
Done

2022-07-29 07:33 UTC, ColdPaleLight commented on display_list/display_list_builder_benchmarks.cc
> +    ->Args({kDefault})
Done

2022-07-29 07:34 UTC, ColdPaleLight commented on display_list/display_list_builder_benchmarks.cc
> +    SkRect clip_bounds = SkRect::MakeLTRB(6.5, 7.3, 90.2, 85.7);
Done. move out of the while loop.

2022-07-29 07:34 UTC, ColdPaleLight commented on display_list/display_list_builder_benchmarks.cc
> +static const int kBoundsAndRtree = 2;
Done.

2022-07-29 07:34 UTC, ColdPaleLight commented on display_list/display_list_builder_benchmarks.cc
> +static const int kDefault = 0;
Done.

2022-07-29 07:45 UTC, ColdPaleLight commented on display_list/display_list_builder_benchmarks.cc
> +  for (auto& group : testing::allRenderingOps) {
Sorry, I didn't understand this comment. So what should I do?

2022-07-29 08:04 UTC, flar commented on display_list/display_list_builder_benchmarks.cc
> +  for (auto& group : testing::allRenderingOps) {
Now that the vectors are inside the .cc files themselves, the namespace isn't an issue any more so the comment is now obsolete.

2022-07-29 08:54 UTC, ColdPaleLight commented
I updated the benchmarks data on the top again.

2022-07-29 18:45 UTC, flar approved these changes
Everything LGTM, autosubmit-ing now to start generating data.

2022-07-29 18:56 UTC, merged

2022-08-02 21:20 UTC, flar commented
I was having trouble finding the results in Skia perf until I realized that the test name was misspelled:

https://flutter-engine-perf.skia.org/e/?queries=executable%3D._display_list_builder_benchmarks

Fix: https://github.com/flutter/engine/pull/35104