Update README.md
flutter/engine pull request #36892
Opened 2022-10-20 11:33 UTC by utkarsh006

- Made the README file concise for better readability of users.
- Formatted some lines of text and removed some of them.
- Added Contributors section and size of the repo.

![Screenshot (234)](https://user-images.githubusercontent.com/94545831/196937146-836f40a8-af27-44ea-a390-95e9bdc90d8e.png)

2022-10-20 13:32 UTC, fzyzcjy commented on README.md
> +To Run/contribute into Flutter Web engine, more tooling can be
uber-nit: Run -> run ;)

2022-10-20 22:17 UTC, fzyzcjy commented on README.md
> +To Run/contribute into Flutter Web engine, more tooling can be
"To Run/contribute into Flutter Web engine" -> To run/contribute into Flutter Web engine?

2022-10-20 22:17 UTC, fzyzcjy commented on README.md
> +To Run/contribute into Flutter Web engine, more tooling can be
anyway just uber nit

2022-10-21 02:54 UTC, utkarsh006 commented
@fzyzcjy Kindly Review Now.

2022-10-21 03:09 UTC, fzyzcjy commented
Hi, I have no permission to *approve* the PR, and I cannot guess what Flutter team thinks about the PR :)

2022-10-21 03:12 UTC, utkarsh006 commented
> Hi, I have no permission to _approve_ the PR, and also impossible to guess what Flutter team thinks about the PR :🧡🧡)

Okay a ton thanks to review it ⭐

2022-10-25 15:47 UTC, utkarsh006 commented
@fzyzcjy Kindly refer this PR to someone who can merge it.

2022-10-27 05:19 UTC, utkarsh006 commented
@jason-simmons Kindly merge the PR.

2022-11-10 21:18 UTC, chinmaygarde requested changes
Thanks for the patch but I don't think this substantially improves the readme. We aren't sure all contributors want this displayed on the README and we don't know if the external service is going to be around.

2022-11-10 21:33 UTC, zanderso commented
Thanks for the patch. After discussion, it seems that folks prefer the README.md as-is, so I'll go ahead and close this. Further discussion can go in the flutter-engine Discord. Cheers!

2022-11-10 21:33 UTC, closed without merging