[WIP] Add web support for FragmentProgram
flutter/engine pull request #37065
Opened 2022-10-27 03:53 UTC by jonahwilliams

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on
writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-10-27 03:54 UTC, jonahwilliams commented on impeller/compiler/impellerc_main.cc
> +      auto stage_data_mapping = switches.use_raw_output
This is a testing hack. Pending the decision for what format to use, we will either leave this as is or add JSON support.

2022-10-27 03:54 UTC, jonahwilliams commented on lib/web_ui/lib/src/engine/canvaskit/painting.dart
> +    // TODO, get uniform length from IPLR.
This is a temporary hack since I dropped all shader metadata to make this work

2022-10-27 03:54 UTC, jonahwilliams commented on lib/web_ui/lib/src/engine/canvaskit/painting.dart
> +    samplers[index] = sampler;
This doesn't seem to be supported by the existiing CanvasKit API

2022-10-27 03:55 UTC, jonahwilliams commented on lib/web_ui/lib/src/engine/canvaskit/painting.dart
> +  }
I don't really understand these APIs, I'm sure that I'm not using the correctly.

2022-10-31 22:31 UTC, hterkelsen requested changes
Please add some tests for RuntimeEffect in canvaskit_api_test.dart

2022-10-31 22:44 UTC, jonahwilliams reviewed
There is a test that creates a RuntimeEffect object - but we don't ever support user supplied SkSL (and we never will). I could generate a small valid SkSL program locally and/or pull it out of an IPLR file to allow writing a test. Is that what you are looking for?

2022-10-31 23:06 UTC, jonahwilliams commented
Updated to use some simple SkSL programs and the RuntimeEffect API

2022-10-31 23:26 UTC, hterkelsen approved these changes
LGTM!

2022-11-01 00:19 UTC, merged