[web] Improve CPU usage when building wasm_release
flutter/engine pull request #37294
Opened 2022-11-03 19:26 UTC by mdebbar

Doing a `felt build` (without `--host`) causes high cpu usage for some people (including me and @htoor3). This is because `autoninja` invokes `ninja` with a high `-j` value of 800.

This PR invokes `ninja` directly for wasm builds, so that we use the default `-j` value of 12.

2022-11-03 19:29 UTC, ditman commented on lib/web_ui/dev/build.dart
> +      host ? 'autoninja' : 'ninja',
```dart
'autoninja',
if (!host)
  '--offline',
```

may do the trick? That instructs autoninja to *not* look for goma, so it'll default to whatever J it deems good for local builds.

2022-11-03 19:33 UTC, ditman approved these changes
LGTM

2022-11-03 20:35 UTC, eyebrowsoffire requested changes
Actually, maybe the right thing is to actually edit `//flutter/tools/gn`. It has a bunch of stuff to try to determine whether to use goma in there, and maybe we should just short circuit that if we're doing a wasm build.

2022-11-03 23:54 UTC, ditman approved these changes
Works on my machine!

2022-11-04 00:07 UTC, eyebrowsoffire approved these changes
LGTM!

2022-11-04 00:43 UTC, Hixie commented
test-exempt: configuration change

2022-11-04 01:37 UTC, merged