[WIP] Fix jank and large-jumping frame by controlling rasterizer ending time (V2)
flutter/engine pull request #37340
Opened 2022-11-05 03:28 UTC by fzyzcjy

(Draft now, create PR just because want to see CI results)

Previous: https://github.com/flutter/engine/pull/36837

2022-11-10 21:26 UTC, dnfield commented on shell/common/rasterizer.cc
> +    }
I am highly skeptical that this will ever be an acceptable approach.

2022-11-10 21:27 UTC, dnfield requested changes
I don't think this is currently in a good state to review - as discussed, we need some benchmarks that would consistently show where this will help and have good reasons to believe it's not making other problems worse.

I'm going to close this to remove it from review queues for now.

2022-11-10 21:27 UTC, closed without merging

2022-11-10 23:36 UTC, fzyzcjy commented
All right, I will try to squeeze some time to make a benchmark later :)

2022-11-23 01:22 UTC, fzyzcjy commented
As discussed in Discord with @dnfield previously, I will firstly focus on the PRs that are critical to the main part of flutter_smooth, and deal with these PRs (which improves performance roughly several FPS per PR) later.