[Web][HTML] Add ImageByteFormat.rawRgba support for Image.toByteData
flutter/engine pull request #39166
Opened 2023-01-26 17:46 UTC by maRci002

Resolves flutter/flutter#89128.

`ImageByteFormat.rawRgba` format was not handled properly as it returned with straight RGBA instead of premultiplied RGBA.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-01-30 10:19 UTC, maRci002 commented
Can anyone help me out whether should I use `webgl2` to determine straight RGBA? @ColdPaleLight @yjbanov

2023-05-16 23:24 UTC, yjbanov requested changes

2023-05-16 23:24 UTC, yjbanov commented on lib/web_ui/lib/src/engine/html_image_codec.dart
> +  ByteBuffer _getStraightRgba() {
(same as in https://github.com/flutter/engine/pull/39109#discussion_r1195766631)

After reading the image data back, set `canvas.width` and `canvas.height` to zero. Safari on iOS will crash if the GC doesn't collect 2D canvases fast enough. Setting the image size to zero causes Safari to free internal image memory immediately.

2023-07-12 05:20 UTC, maRci002 commented
Unfortunately I don't have any free time in the near future to update this PR.

2023-07-12 06:29 UTC, closed without merging