[Impeller] Don't use waitUntilScheduled on iOS
flutter/engine pull request #40768
Opened 2023-03-29 19:58 UTC by bdero

2023-03-29 20:00 UTC, chinmaygarde approved these changes

2023-03-29 20:32 UTC, dnfield requested changes
Want to make sure this doesn't land without getting some more context in the code this time.

2023-03-29 22:44 UTC, bdero commented on impeller/renderer/backend/metal/command_buffer_mtl.mm
> +#if (FML_OS_MACOSX || FML_OS_IOS_SIMULATOR)
Alrighty, done.

2023-03-30 02:31 UTC, dnfield commented on impeller/renderer/backend/metal/command_buffer_mtl.mm
> +#if (FML_OS_MACOSX || FML_OS_IOS_SIMULATOR)
Are there any instructions on how to reproduce the issue seen? E.g. `Run wonderous app on a simulator on an arm mac host`?

2023-03-30 02:40 UTC, chinmaygarde commented on impeller/renderer/backend/metal/command_buffer_mtl.mm
> +#if (FML_OS_MACOSX || FML_OS_IOS_SIMULATOR)
Yeah, thats pretty much exactly it.

2023-03-30 04:04 UTC, dnfield approved these changes

2023-03-30 04:06 UTC, merged