Update Dart pub package revision.
flutter/engine pull request #40946
Opened 2023-04-05 17:59 UTC by lrhn

Changes needed to land Dart SDK CL.

A small update to Pub needed to allow some `interface` modifiers to be added to the Dart SDK libraries.

Needs to be landed (and rolled to mono-repo) before SDK CL can land.

2023-04-05 18:03 UTC, devoncarew commented
Here's the diff from dart-lang/pub for posterity: https://github.com/dart-lang/pub/compare/196e89e5716d64b2954021e6ac9bb5a20d975fc6..f0613dc67423976f1c13cc871e6ddf6db17793b0 .

2023-04-05 18:04 UTC, devoncarew approved these changes

2023-04-05 18:13 UTC, zanderso requested changes
What is the reason for updating this manually? Normally this would be updated in the PR that the autoroller creates when rolling the Dart SDK.

2023-04-05 18:43 UTC, lrhn commented
So the process would be to (get the Pub change landed and)
make a Dart CL to change the Pub rev in the Dart DEPS file and land that.
Then get that rolled into Flutter.
Then get that rolled into the internal mono-repo. 
Then I'd be able to land the Dart CL depending on it.

2023-04-05 19:26 UTC, lrhn commented
My (very recent) experience is that a change in the Dart SDK which depends on a change in the Flutter SDK, can get rolled into G3 independently of Flutter, break the old version of Flutter in G3, and get summarily reverted.
I'd prefer to avoid the extra cycle of revert and reland.

2023-04-25 19:36 UTC, zanderso commented
Closing as presumed stale. Feel free to reopen and rebase if I'm mistaken.

2023-04-25 19:36 UTC, closed without merging