Close connection on keyboard close
flutter/engine pull request #41500
Opened 2023-04-26 02:51 UTC by ksballetba

Fix:
- https://github.com/flutter/flutter/issues/123523
- https://github.com/flutter/flutter/issues/124890

### Before this patch:

https://user-images.githubusercontent.com/30322203/228413196-29c57bb0-3220-495b-9e73-f58777de440f.mp4

### After this patch:

https://user-images.githubusercontent.com/30322203/228413249-fc06f49d-6579-4476-9788-90f12a53b8c3.mp4

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

2023-04-27 18:40 UTC, mossmana requested changes

2023-05-04 02:45 UTC, ksballetchan commented on shell/platform/android/io/flutter/embedding/engine/systemchannels/TextInputChannel.java
> +    Log.v(TAG, "Sending 'onConnectionClosed' message.");
Because other function in `TextInputChannel`  has same log.

2023-05-04 02:49 UTC, ksballetchan commented on shell/platform/android/io/flutter/embedding/engine/systemchannels/TextInputChannel.java
> +    Log.v(TAG, "Sending 'onConnectionClosed' message.");
![image](https://user-images.githubusercontent.com/127334265/236100652-128741f7-e857-4ae4-9173-172a6749c14f.png)

2023-05-04 18:42 UTC, mossmana commented on shell/platform/android/io/flutter/embedding/engine/systemchannels/TextInputChannel.java
> +    Log.v(TAG, "Sending 'onConnectionClosed' message.");
Sounds good! LGTM!

2023-05-04 18:42 UTC, mossmana approved these changes

2023-05-05 02:54 UTC, luckysmg commented
The code diff between this and https://github.com/flutter/engine/pull/40746 is only adding a 
```
@VisibleForTesting(otherwise = VisibleForTesting.PACKAGE_PRIVATE)
```
on `ImeSyncDeferringInsetsCallback` to solve the lint issue 
So I think LGTM ^_^

2023-05-05 02:54 UTC, luckysmg approved these changes

2023-05-05 02:54 UTC, luckysmg commented
Adding label for merging, let's see if the issue gone ^_^

2023-05-05 02:55 UTC, merged

2023-12-12 20:45 UTC, DBOutlink commented
From the tests I have done this is not the default behavior of a native Android app: in fact when the keyboard is hidden the text field maintains focus