[linux] Allow oberriding aot_library_path
flutter/engine pull request #42555
Opened 2023-06-05 01:21 UTC by dballard

Support overriding `aot_library_path` in `FLDartProject` on Linux.

Fixes: https://github.com/flutter/flutter/issues/128213

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-06-12 05:03 UTC, robert-ancell requested changes
Seems to be missing the code to pass this path to the engine?

2023-06-12 05:03 UTC, robert-ancell commented on shell/platform/linux/fl_dart_project.cc
> +                                                          gchar* path) {
Use 'const gchar*'

2023-06-12 05:03 UTC, robert-ancell commented on shell/platform/linux/public/flutter_linux/fl_dart_project.h
> + * @project: an #FlDartProject.
Missing '@path: ...'

2023-06-12 05:03 UTC, robert-ancell commented on shell/platform/linux/public/flutter_linux/fl_dart_project.h
> +void fl_dart_project_set_aot_library_path(FlDartProject* project, gchar* path);
Use 'const gchar*'

2023-06-22 18:16 UTC, loic-sharma commented
@dballard Have you had a chance to address the feedback? (Desktop triage)

2023-06-22 18:56 UTC, dballard commented
@loic-sharma Not yet, been a busy few weeks but hoping to get back to this in the next few days, thanks for the reminder!

2023-07-08 17:47 UTC, dballard commented
> Seems to be missing the code to pass this path to the engine?

How so? I copied what `fl_dart_project_set_icu_data_path` does. Doing this from with in my own code seemed to be sufficient.

2023-07-09 21:52 UTC, robert-ancell commented
> > Seems to be missing the code to pass this path to the engine?
> 
> How so? I copied what `fl_dart_project_set_icu_data_path` does. Doing this from with in my own code seemed to be sufficient.

Sorry, yes. I missed the existing code was already there to do this.

2023-07-09 21:53 UTC, robert-ancell commented on shell/platform/linux/public/flutter_linux/fl_dart_project.h
> + * @path: the absolute path to the assets directory.
Copy/paste error.

2023-07-09 21:53 UTC, robert-ancell commented on shell/platform/linux/public/flutter_linux/fl_dart_project.h
> + * @path: the absolute path to the assets directory.
Other than this small fix this looks good, thanks!

2023-07-10 04:11 UTC, robert-ancell approved these changes
LGTM

2023-07-10 04:11 UTC, merged