[Impeller] Reland: Added a switch to turn on vulkan
flutter/engine pull request #42669
Opened 2023-06-08 17:45 UTC by gaaclarke

relands https://github.com/flutter/engine/pull/42585

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-06-08 22:15 UTC, jason-simmons requested changes
This is still adding the Impeller Vulkan backend to release binaries because `impeller_enable_vulkan` is on by default for Android.

(see https://github.com/flutter/engine/blob/main/impeller/tools/impeller.gni#L21)

2023-06-08 22:15 UTC, jason-simmons commented on shell/platform/android/BUILD.gn
> +    defines += [ "IMPELLER_ENABLE_VULKAN" ]
This is not needed.  `IMPELLER_ENABLE_VULKAN` will be defined in this module through the dependency on Impeller's public config.

2023-06-08 22:19 UTC, gaaclarke commented
> This is still adding the Impeller Vulkan backend to release binaries because `impeller_enable_vulkan` is on by default for Android.
> 
> (see https://github.com/flutter/engine/blob/main/impeller/tools/impeller.gni#L21)

Ahh shoot. I didn't think to look there, I only looked at the builders and gn script.  Having that flag on seems in error since we are saying we don't want it.  I'm guessing it was just a hack to get CI compilation coverage.

2023-06-09 17:26 UTC, zanderso approved these changes
cc @jonahwilliams @dnfield

2023-06-09 17:45 UTC, jason-simmons approved these changes

2023-06-09 18:35 UTC, merged