ParagraphStyle uses the wrong bit mask
flutter/engine pull request #43070
Opened 2023-06-22 04:46 UTC by fzyzcjy

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-06-22 20:11 UTC, chinmaygarde approved these changes

2023-06-22 20:12 UTC, chinmaygarde commented
The test failures are related. cc @jason-simmons

2023-06-22 20:33 UTC, jason-simmons requested changes

2023-06-22 20:33 UTC, jason-simmons commented on lib/ui/text.dart
> +             'strutStyle: ${    _encoded[0] & 0x200 == 0x200 ? _strutStyle                       : "unspecified"}, ',
These bit masks must match the bits that are set in `_encodeParagraphStyle` (https://github.com/flutter/engine/blob/main/lib/ui/text.dart#L1671)

The order of the bits after `fontSize` is:
* `height`
* `strutStyle`
* `ellipsis`
* `locale`

Also, there should not be a comma after the closing quote of this string.  (The comma is causing the engine build failures in the CI checks)

2023-06-26 18:12 UTC, jason-simmons approved these changes

2023-06-26 18:58 UTC, merged