Web html emoji issule fix
flutter/engine pull request #44247
Opened 2023-08-02 03:52 UTC by zjrwdl

Emoji display problem in flutter web html render #131337

before this pr:
![image](https://github.com/zjrwdl/engine/assets/6874049/c3513ca3-fc3c-428d-988a-ece8e9fba61b)

after this pr:
![image](https://github.com/zjrwdl/engine/assets/6874049/ff8d59ff-ff98-45d5-8b9a-698c3801f455)

*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/issues/131337

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-10-23 23:13 UTC, gildaswise commented
Hey, is this fix still planned? I'm also having issues with the html renderer with other ZWJ emojis 

<img width="324" alt="image" src="https://github.com/flutter/engine/assets/1339236/c00a4d5d-a66f-4be0-8cb5-1bfedc8646ed">

2023-12-05 23:23 UTC, harryterkelsen commented
https://github.com/flutter/engine/pull/44247#issuecomment-1661950687

Your PR affects text layout, and the failing tests are related to text layout. Please resolve the failing tests. Also, please add a new test which will fail before your change and which succeeds after your change.

2024-02-06 23:50 UTC, goderbauer commented
(triage) @zjrwdl Just checking in to see if you still have plans to address the feedback given above?

2024-03-25 19:41 UTC, mdebbar requested changes

2024-03-25 19:41 UTC, mdebbar commented on lib/web_ui/lib/src/engine/text/canvas_paragraph.dart
> +        spanElement.appendText(fullText);
It looks like you are putting the entire line into a single `<span>` element, is that correct?

This won't work. One line of text could contain fragments with different styles. You can't just put all of them in the same `<span>` with the same style.

2024-05-28 22:59 UTC, goderbauer commented
(triage) @zjrwdl Do you still have plans to come back and address the feedback given above? Thank you.

2024-08-06 22:51 UTC, goderbauer commented
I am going to close this one since there was no follow-up. Feel free to reopen if you find the time to work on this again. Thank you.

2024-08-06 22:51 UTC, closed without merging