update min ios target for testing to 17.0
flutter/engine pull request #44852
Opened 2023-08-18 17:53 UTC by cyanglaz

Update min iOS deploy target for testing for 17.0

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-08-21 19:55 UTC, cyanglaz commented
When this lands successfully and pass tests post commit, I will follow up with a patch to updating the variable directly, then revert hard code value here.

2023-08-21 19:57 UTC, cyanglaz commented
@hellohuanlin 
`@available(iOS 17) ` returns true when we set the min deploy version to ios 17 even when the simulator is ios 16, I'm changing it to use `NSProcessInfo` for a more accurate version check on device.

2023-08-22 18:16 UTC, hellohuanlin commented
> @available(iOS 17)  returns true when we set the min deploy version to ios 17 even when the simulator is ios 16

I'm confused. If min deployment version is 17, how can it run on ios 16? Or am i missing something?

2023-08-22 19:29 UTC, cyanglaz commented
> I'm confused. If min deployment version is 17, how can it run on ios 16? Or am i missing something?

Sorry I wasn't clear in the PR title. It is updating the c flag`-mios-simulator-version-min` to 17.0 when building the testing library. The min deployment target is still the one set in the xcproj.

2023-08-23 17:53 UTC, hellohuanlin approved these changes
as discussed offline, reminder to 
1. fix the missing `@available(iOS 17.0, *)`
2. comment why we need this change

2023-08-23 20:26 UTC, cyanglaz commented
After offline discussion with @stuartmorgan, we think it is better to ignore the warning for now instead of updating the flag.

2023-08-23 20:28 UTC, hellohuanlin approved these changes
LGTM

2023-08-24 13:47 UTC, stuartmorgan requested changes

2023-08-24 13:47 UTC, stuartmorgan commented on shell/platform/darwin/ios/BUILD.gn
> +  cflags_objcc = [ "-Wno-unguarded-availability-new" ]
Please add a comment explaining why this is here, and what the conditions are for getting rid of it (i.e., the XCTest header bug being fixed).

2023-08-24 13:47 UTC, stuartmorgan commented on shell/platform/darwin/ios/BUILD.gn
> +  cflags_objcc = [ "-Wno-unguarded-availability-new" ]
Same.

2023-08-25 16:46 UTC, stuartmorgan approved these changes
LGTM with nit. Thanks!

2023-08-25 16:46 UTC, stuartmorgan commented on shell/platform/darwin/ios/BUILD.gn
> +  # An XCode15-beta has a bug where iOS 17 API usage is not guarded.
Nit: Xcode 15 beta

2023-08-25 16:46 UTC, stuartmorgan commented on shell/platform/darwin/ios/BUILD.gn
> +  # An XCode15-beta has a bug where iOS 17 API usage is not guarded.
Same.

2023-08-25 17:31 UTC, merged