Fixes stroke path geometry that can draw outside of path if the path …
flutter/engine pull request #45252
Opened 2023-08-29 22:45 UTC by chunhtai

…ends at sharp turn

fixes https://github.com/flutter/flutter/issues/133032

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt. See [testing the engine] for instructions on writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-08-30 21:11 UTC, chunhtai commented on impeller/entity/geometry/stroke_path_geometry.cc
> -      vtx.position = polyline.points[point_i] + offset;
Reasoning https://github.com/flutter/flutter/issues/133032#issuecomment-1698114342

2023-08-30 21:15 UTC, chunhtai commented
oops looks like the golden has failed

2023-09-01 23:09 UTC, chunhtai commented
The circle golden is missing a tiny tiny slide of pixels which i think should be fine. 

@bdero This is ready for review now

2023-09-05 18:59 UTC, chinmaygarde approved these changes
LGTM but @bdero is more familiar with this code and may have thoughts.

Thanks so much!

2023-09-05 19:00 UTC, bdero requested changes
This patch introduces regressions with most strokes (visible in EntityTest.StrokeCapAndJoinTest).

2023-09-05 19:02 UTC, bdero commented
https://github.com/flutter/engine/assets/919017/2776c7b9-9f93-4dc2-afa6-f1f7f81b2155

2023-09-05 19:02 UTC, chunhtai commented
@bdero will take a look. Should we include all the playground test into goldens?

2023-09-05 19:05 UTC, chunhtai commented
I think I know the problem is, so the point order matters. for a complete retangle 
```
tl -------tr
|               |
bl-------br
```
the point needs to be provided in either of this order
tl, bl, tr, br
or
bl, tl, br, tr

2023-09-05 19:18 UTC, bdero commented
We should add a new golden that draws some stroke paths similar to this in `aiks_unittests.cc` to make this easier catch.

BTW, to help debug, you can also use the Z key when viewing a playground. 
It looks like there's also a bug in the miter joint logic:

https://github.com/flutter/engine/assets/919017/33e1c870-856a-4173-bf6e-a1b243335fa2

2023-09-05 19:56 UTC, bdero commented
I think the thesis of this patch is not really correct/the full picture? I wrote a Skia fiddle to render the given problem stroke and Skia renders it the way that we do:

https://fiddle.skia.org/c/0c12e8b2a46224c97b84bb6a0519d580

![image](https://github.com/flutter/engine/assets/919017/68672435-f576-43fe-a13b-6e661b2a3ab2)

2023-09-05 20:11 UTC, bdero commented
Looking at the original issue, I suspect the problem is related to how we're managing the forward direction/normals for caps: https://github.com/flutter/flutter/issues/133032#issuecomment-1707243488

2023-09-05 20:22 UTC, chunhtai commented
I did the frame capturing, I did see the small overdraw of the original issue was due to the line I removed in https://github.com/flutter/engine/pull/45252#discussion_r1310829933 (there are at least 3 or 4 points before the end of the line that draws outside of the end cap)

It doesn't seem to related to cap drawing?

2023-09-05 22:27 UTC, bdero commented
Talked about this offline a bit, summarizing here:

I believe the root problem is that we always use the same normal for the start and end of the line rects. This works great for line contours, but is not ideal for cubics/quadratics, especially for tight curves.

For cubic/quadratic contours specifically, we need to skip the last two points when drawing polyline segments.

A couple of possible approaches for this:

1. The "perfect" approach: `impeller::PolylineContour` can track a `bool is_curve` member that is populated when generating the polyline, and whenever it's true, assume the angle between the two points if small enough such that we don't need to append the last two points for each polyline rectangle segment.
2. Imperfect quick n' dirty approach: if the next line segment normal `n` is very close to the angle of the current line segment normal `c`, then don't draw the 3rd/4th point of the polyline segment rectangle. `c.Dot(n) > 1 - small_number`.

(Although I think approach 2 is probably more trouble than it's worth TBH :))

2023-09-08 19:06 UTC, chunhtai commented
The circle golden has just a tiny difference, I assume it is ok

2023-09-08 20:44 UTC, bdero reviewed
I'm seeing issues with curves. It appears that all the triangles are there, but the offset is winding up 0 length sometimes.

https://github.com/flutter/engine/assets/919017/76354fb5-27e1-438b-97e6-1a63b261aed2

2023-09-08 20:44 UTC, bdero commented on impeller/entity/geometry/stroke_path_geometry.cc
> +      // assuming the angles between of a continous two points are close enough.
```suggestion
      // For line components, two additional points need to be appended prior
      // to appending a join connecting the next component. But for curve
      // components, we assume that the polyline is detailed enough such that
      // we can avoid worrying about joins altogether.
```

2023-09-08 20:44 UTC, bdero commented on impeller/entity/geometry/stroke_path_geometry.cc
>      } else {
Now that we know when we're in a curve or not, we should also be able to get away with removing joins (not calling `join_proc` right below) for curves.

2023-09-08 20:44 UTC, bdero commented on impeller/geometry/path_component.h
> +// A component represets a Quadratic Bézier curve.
```suggestion
// A component that represents a Quadratic Bézier curve.
```

2023-09-08 20:44 UTC, bdero commented on impeller/geometry/path_component.h
> +// A component represets a Cubic Bézier curve.
```suggestion
// A component that represents a Cubic Bézier curve.
```

2023-09-12 21:52 UTC, chunhtai commented on impeller/entity/geometry/stroke_path_geometry.cc
> +        // need to be drawn with the contour end_direction.
This is in case for contour is_closed, the join assume the two endpoints are drawn

2023-09-12 21:53 UTC, chunhtai commented
I also added a new golden test that similar to the cubic component playground

2023-09-13 17:10 UTC, bdero reviewed
`EntityTest.StrokeCapAndJoinTest` still doesn't look right. This is the line I use to build and run it:

```
autoninja -C ../out/host_debug_unopt/ -j 1000 flutter/impeller:impeller_unittests && ../out/host_debug_unopt/impeller_unittests --timeout=0 --gtest_filter="Play/EntityTest.StrokeCapAndJoinTest/Metal" --enable_playground
```

![Screenshot 2023-09-13 at 10 11 29 AM](https://github.com/flutter/engine/assets/919017/60081170-991b-49b6-a3ec-7a1862281096)

2023-09-13 17:15 UTC, bdero commented
Ah hold on one sec, I think I screwed up the checkout locally.

2023-09-13 17:20 UTC, bdero approved these changes
LGTM! Thanks a lot for your work on this! :)

2023-09-13 17:23 UTC, bdero commented
The goldens are looking good and I marked them as positive.

2023-09-13 17:25 UTC, bdero commented on impeller/entity/geometry/stroke_path_geometry.cc
> +        // need to be drawn with the contour end_direction.
Ah right, that makes sense.

2023-09-13 17:27 UTC, merged