[Impeller] faster path for circle geometry, rename.
flutter/engine pull request #47845
Opened 2023-11-09 02:11 UTC by jonahwilliams

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-11-09 21:35 UTC, bdero approved these changes
LGTM, just a couple of suggestions. Feel free to punt, of course.

2023-11-09 21:35 UTC, bdero commented on impeller/entity/geometry/circle_geometry.cc
> +    angle_table[i] = Point(cos(elapsed_angle), sin(elapsed_angle)) * radius;
Instead of generating a table for the whole circle, you could just generate points for the 0 to PI/2 range and reuse the table for all 4 quadrants.

2023-11-09 21:35 UTC, jonahwilliams commented
From offline discussion: this code can be simplified by using a Triangle strip.

2023-11-09 22:21 UTC, jonahwilliams commented
I think this looks right but I want to double check goldens.

2023-11-09 22:52 UTC, jonahwilliams commented
Testing BTW

2023-11-10 04:15 UTC, jonahwilliams commented on impeller/entity/geometry/circle_geometry.cc
> +            points[offset++] = pt2;
Ahh, I had a brain fart. The reason this wasn't working is that this code is also used for draw points, so I'd also need to insert padding to break the strip. I'd rather leave this as is for now.

2023-11-10 11:26 UTC, flar requested changes

2023-11-10 11:26 UTC, flar commented on impeller/entity/geometry/circle_geometry.cc
> +  Scalar min_size = 1.0f / sqrt(std::abs(determinant));
min_size is appropriate for strokes (i.e. when this is created from DrawPoints), but not when we are filling an actual circle (i.e. when created from DrawCircle).

2023-11-10 20:11 UTC, flar commented
One general comment is that I think it might be more useful to split this into Circle and Point geometry classes, but have their common code shared either via global/static methods that tesselate a circle or through a parent "CircleTesselatingGeometry" mixin class to inherit from. While both DrawPoints and DrawCircle may end up tesselating a circle, they generate them from different kinds of data and have different options. For example, DrawPoints may not involve circles at all and even when it does generate circles it will need to filter the radius through the minimum scale before it invokes the tesselation. A couple of lines of code in the split Geometry classes can do this work and then delegate to a common tesselation mechanism.

2023-11-17 17:55 UTC, jonahwilliams commented
Closing in favor of https://github.com/flutter/flutter/issues/138254

2023-11-17 17:55 UTC, closed without merging

2023-11-17 17:55 UTC, jonahwilliams commented
Oops i mean: https://github.com/flutter/flutter/issues/138254