fix: web canvaskit fragment shaders were not using updated uniform values
flutter/engine pull request #53246
Opened 2024-06-06 09:34 UTC by Moncader

This fixes an issue where in CanvasKit builds, uniforms set in setFloat function in the Paint class don't get updated after the initial render.
For example, like in the issue linked below, having a shader that animates a value over time and you want to reuse the Paint object that the shader is set to.

I'm no expert with CanvasKit nor with the Flutter Engine, but from what I could tell it seemed that the uniforms were only being sent to Skia on creation of the shader via _makeEffect.

However, any uniforms set afterwords were just stored in a local dart-side List<double> and forgotten about.

This PR changes the List<double> to use a WASM backed SkFloat32List to keep the references to the uniforms linked to dart-side.

fixes https://github.com/flutter/flutter/issues/149800

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I signed the [CLA].
- [ ] All existing and new tests are passing.

2024-06-06 09:36 UTC, Moncader commented
I'll get to writing tests (if possible for gl related issues on the web?) and add it here soon.
Do golden tests even work with shaders?

2024-06-06 09:38 UTC, mr-durjoy reviewed
These changes correctly address the issue of uniforms not updating in CanvasKit builds. Ensure comprehensive testing to validate the changes.

2024-06-07 18:14 UTC, eyebrowsoffire commented
`test/canvaskit/canvaskit_api_test.dart` is broken with this change and needs to be updated.

2024-06-11 00:46 UTC, Moncader commented
The golden is incorrect and so far I'm not sure why.
I'll slowly work it out over the next few days. (the golden seems to be affected by the previous test and is showing the 25px version on the 10px test even though it's a new paint object.

I assume it's a bug on my side but I'd also like to know if as a rule in this flutter engine golden test system you can't re-use a golden test file in a single test like I am for this one?

2024-06-14 07:01 UTC, Moncader commented
I've confirmed on my local machine that this is not a bug on my side. But the golden tests are producing different results in CI than Chrome is showing per-frame on my local machine.

Does the golden system have some kind of restriction where you aren't allowed to use multiple of the same golden file?

2024-06-17 17:37 UTC, IntensiCode commented
@Moncader just stumbled across your PR after running into this issue. currently using the new `Paint()` for every frame as a work-around. anyway, is there anything I can do to help out with this PR?

2024-06-18 00:56 UTC, Moncader commented
@IntensiCode The support and fix is complete. I'm waiting on someone to give some insight on how the golden test system works due to the test saying there's a diff when there isn't actually a diff when confirmed locally.

I'm asking over on discord as well.

2024-06-18 17:20 UTC, eyebrowsoffire requested changes

2024-06-18 17:20 UTC, eyebrowsoffire commented on lib/web_ui/test/ui/fragment_shader_test.dart
> +    await drawCircleReusePaint('fragment_shader_voronoi_tile25px.png');
You can't reuse the same golden name for these screenshots. Just make a unique golden name for these new ones.

```suggestion
    await drawCircleReusePaint('fragment_shader_voronoi_tile10px_reuse_paint.png');

    // Make sure we can reuse the shader object with a new uniform value and the same Paint object.
    shader.setFloat(0, 25.0);
    await drawCircleReusePaint('fragment_shader_voronoi_tile25px_reuse_paint.png');
```

2024-06-19 01:47 UTC, eyebrowsoffire commented
The goldens seem to indicate that this issue exists in the skwasm renderer as well and needs to be fixed. I can look into that in a followup though.

2024-06-19 02:57 UTC, Moncader commented
I'll check it out first actually. I don't mind getting my feet wet there. (assuming the issue ends up being a simple fix like this one was)

2024-06-20 16:45 UTC, eyebrowsoffire commented
I think the fix for the skwasm side should just be here: https://github.com/flutter/engine/blob/main/lib/web_ui/skwasm/shaders.cpp#L134

Instead of doing `SkData::MakeWithCopy(uniforms->data(), uniforms->size())`, we should just use the existing `SkData` object by doing `sk_ref_sp(uniforms)`

2024-06-20 16:46 UTC, eyebrowsoffire requested changes

2024-06-20 16:46 UTC, eyebrowsoffire commented on lib/web_ui/lib/src/engine/canvaskit/painting.dart
> +      : floats = mallocFloat32List(floatCount + textureCount * 2),
Since we `malloc`'d this list, we also need to free it in `dispose`

2024-06-21 00:33 UTC, Moncader commented
> I think the fix for the skwasm side should just be here: https://github.com/flutter/engine/blob/main/lib/web_ui/skwasm/shaders.cpp#L134
> 
> Instead of doing `SkData::MakeWithCopy(uniforms->data(), uniforms->size())`, we should just use the existing `SkData` object by doing `sk_ref_sp(uniforms)`

This is what I was thinking as well, but wasn't sure if it's safe to use the reference like that.
Is there a guarantee that those uniforms won't be free'd or swapped to a different object somewhere else?

2024-06-21 19:05 UTC, eyebrowsoffire commented
> > I think the fix for the skwasm side should just be here: https://github.com/flutter/engine/blob/main/lib/web_ui/skwasm/shaders.cpp#L134
> > Instead of doing `SkData::MakeWithCopy(uniforms->data(), uniforms->size())`, we should just use the existing `SkData` object by doing `sk_ref_sp(uniforms)`
> 
> This is what I was thinking as well, but wasn't sure if it's safe to use the reference like that. Is there a guarantee that those uniforms won't be free'd or swapped to a different object somewhere else?

It's managed by a smart pointer `sk_sp` so it should keep it alive as long as it is needed.

2024-06-25 08:41 UTC, Moncader commented
The test looks good now. Seems I don't have permission to say OK to the golden though?

2024-06-25 15:04 UTC, eyebrowsoffire approved these changes
I went ahead and approved the goldens. Thanks for the fix!

2024-06-25 16:51 UTC, yjbanov approved these changes
![lgtm](https://user-images.githubusercontent.com/211513/32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d.png)

2024-06-25 17:59 UTC, merged