[CP] [skwasm] Fix platform view occlusion logic.
flutter/engine pull request #54871
Opened 2024-08-29 16:18 UTC by Rexios80

Cherry-pick of https://github.com/flutter/engine/pull/54061

2024-08-29 16:31 UTC, eyebrowsoffire approved these changes
Cherry pick looks good to me! Thanks!

2024-08-29 16:53 UTC, eyebrowsoffire requested changes
Looks like CI is failing, I'm guessing some there are some test changes that didn't make it over in the CP for some reason?

2024-08-29 16:58 UTC, Rexios80 commented on lib/web_ui/test/engine/scene_builder_test.dart
> +      if (expectedView.bounds != actualView.bounds) {
@eyebrowsoffire There was a merge conflict here. Did I resolve it incorrectly?

2024-08-29 16:59 UTC, Rexios80 commented on lib/web_ui/test/engine/scene_builder_test.dart
> +      if (expectedView.bounds != actualView.bounds) {
Indeed I did

2024-08-29 17:12 UTC, Rexios80 commented
Also I did notice that there is a `flutter-3.24-candidate.1` branch. Is `flutter-3.24-candidate.0` the correct one? The https://github.com/flutter/flutter/blob/stable/bin/internal/release-candidate-branch.version file points to `flutter-3.24-candidate.0`.

2024-09-05 15:49 UTC, eyebrowsoffire approved these changes
Looks good! I'm not 100% sure about which branch should be targeted, I'll let the release team handle that particular question.

2024-09-10 15:38 UTC, merged