[CP-stable]Add xcprivacy privacy manifest to macOS framework
flutter/engine pull request #55366
Opened 2024-09-23 17:46 UTC by flutteractionsbot

This pull request is created by [automatic cherry pick workflow](https://github.com/flutter/flutter/blob/main/docs/releases/Flutter-Cherrypick-Process.md#automatically-creates-a-cherry-pick-request)
Please fill in the form below, and a flutter domain expert will evaluate this cherry pick request.

### Issue Link:
What is the link to the issue this cherry-pick is addressing?

< Replace with issue link here >

### Changelog Description:
Explain this cherry pick in one line that is accessible to most Flutter developers. See [best practices](https://github.com/flutter/flutter/blob/main/docs/releases/Hotfix-Documentation-Best-Practices.md) for examples

< Replace with changelog description here >

### Impact Description:
What is the impact (ex. visual jank on Samsung phones, app crash, cannot ship an iOS app)? Does it impact development (ex. flutter doctor crashes when Android Studio is installed), or the shipping production app (the app crashes on launch)

< Replace with impact description here >

### Workaround:
Is there a workaround for this issue?

< Replace with workaround here >

### Risk:
What is the risk level of this cherry-pick?

  - [ ] Low
  - [ ] Medium
  - [ ] High

### Test Coverage:
Are you confident that your fix is well-tested by automated tests?

  - [ ] Yes
  - [ ] No

### Validation Steps:
What are the steps to validate that this fix works?

< Replace with validation steps here >

2024-10-18 05:09 UTC, jmagman requested changes

2024-10-18 05:09 UTC, jmagman commented on shell/platform/darwin/macos/BUILD.gn
> +  outputs = [ "$_flutter_framework_dir/PrivacyInfo.xcprivacy" ]
The path is actually incorrect and it was caught during beta codesigning https://github.com/flutter/flutter/issues/157016

The outputs should be changed to 

```suggestion
  outputs =
      [ "$_flutter_framework_dir/Versions/A/Resources/PrivacyInfo.xcprivacy" ]
```

Beta patch was at https://github.com/flutter/engine/pull/55938

2024-10-18 05:09 UTC, jmagman commented on shell/platform/darwin/macos/BUILD.gn
> +  outputs = [ "$_flutter_framework_dir/PrivacyInfo.xcprivacy" ]
Let's hold off until we confirm the beta cp passes codesigning.

2024-10-23 18:44 UTC, jmagman approved these changes

2024-10-23 21:58 UTC, merged

2025-02-07 09:05 UTC, bobin-abraham commented
Hi Team,

I am still able to reproduce this issue . I am using the Flutter version "Channel stable, 3.27.4, on macOS 15.1.1 24B91 darwin-arm64, locale en-IN) . 

On every MacOS build released for either Beta testing or App Store is making the warning email.

Adding the warning email content for your reference 

"ITMS-91061: Missing privacy manifest - Your app includes “Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS”, which includes Flutter, an SDK that was identified in the documentation as a commonly used third-party SDK. Starting February 12, 2025, if a new app includes a commonly used third-party SDK, or an app update adds a new commonly used third-party SDK, the SDK must include a privacy manifest file or you won’t be able to submit the app for review in App Store Connect. Please contact the provider of the SDK that includes this file to get an updated SDK version with a privacy manifest. For more details about this policy, including a list of SDKs that are required to include signatures and manifests, visit: https://developer.apple.com/support/third-party-SDK-requirements."


Please fix this issues ASAP, because the last date is Feb 12th

2025-02-07 11:16 UTC, stuartmorgan commented
@bobin-abraham Please file issues in the issue tracker.

2025-02-17 07:40 UTC, chengxuyuanzzy commented
@bobin-abraham Has it been solved?

2025-02-17 08:10 UTC, bobin-abraham commented
@chengxuyuanzzy  Yes the issue is solved. We upgraded Connectivity_plus to version 6.1.3 . 

After that we released few builds to App Store and none of them got any warnings.