[iOS] option to enable suggestions with autocorrect off
flutter/engine pull request #56859
Opened 2024-11-28 09:33 UTC by jan-swiezynski

There is no possibility on iOS to leave the auto-suggest bar visible and have the autocorrection turned off when showing `TextField`. Tapping outside `TextField` with autocorrection on fills the `TextField` with suggestion and it's not always an intended behaviour.

![Autocorrection on](https://github.com/user-attachments/assets/a435831b-e303-42c3-8da3-ad182987c6aa)

![Autocorrection off, enableSuggestion on](https://github.com/user-attachments/assets/8aa60b66-a351-4476-a935-9eee2d9a1027)

Fixes https://github.com/flutter/flutter/issues/159584

Removed 1 Test.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I signed the [CLA].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[C++, Objective-C, Java style guides]: https://github.com/flutter/engine/blob/main/CONTRIBUTING.md#style
[testing the engine]: https://github.com/flutter/flutter/wiki/Testing-the-engine
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2024-12-04 16:28 UTC, cbracken requested changes
I've left style/testing comments inline, but at a much higher level, I'm not entirely whether `enableSuggestions` is the right approach here.

[`EditableText`](https://api.flutter.dev/flutter/widgets/EditableText-class.html) widgets have a `spellCheckConfiguration` property that holds a [`SpellCheckConfiguration`](https://api.flutter.dev/flutter/widgets/SpellCheckConfiguration-class.html). I would have assumed that passing [`SpellCheckConfiguration.disabled`](https://api.flutter.dev/flutter/widgets/SpellCheckConfiguration/SpellCheckConfiguration.disabled.html) would be the way to do this.

@justinmc will know the answer to that question.

2024-12-04 16:28 UTC, cbracken commented on shell/platform/darwin/ios/framework/Source/FlutterTextInputPluginTest.mm
> -
Please don't delete tests for existing behaviour; they were added for a reason. 

You'll need to update the existing test to reflect the new expected behaviour and add additional testing to cover all four combinations of autocorrect/enableSuggestions.

2024-12-04 18:27 UTC, bleroux commented on shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
> +      disableSuggestions ? UITextSpellCheckingTypeNo : UITextSpellCheckingTypeDefault;
> The [enableSuggestions API docs](https://api.flutter.dev/flutter/widgets/EditableText/enableSuggestions.html) currently state that this flag only affects Android. @bleroux do you know the background on why we don't apply it to iOS as well?

I don't know the background. The documentation landed in https://github.com/flutter/flutter/pull/42550. It seems that this was implemented to match an Android feature. Maybe something similar did not exist on the iOS side at that time?

2024-12-04 21:32 UTC, justinmc reviewed
To be clear on iOS these are the three features we're talking about here:

| Spell check | Suggestions | Autocorrect |
| --- | --- | --- |
| Red underline, red highlight, and suggestion dialog for misspelled words. | Completion suggestions that appear above the software keyboard as the user types. If a hardware keyboard is used instead, there is a blue highlight and a suggestion dialog. | Automatic replacement of common typos. |
| Disabled by default, enable with `spellCheckConfiguration: SpellCheckConfiguration()`. | Enabled by default, disable with `autocorrect: false`. After this PR, would instead be disabled with `enableSuggestions: false`. | Enabled by default, disable with `autocorrect: false`. |
| <img width="270" alt="Screenshot 2024-12-04 at 1 06 36 PM" src="https://github.com/user-attachments/assets/a07d9c40-44fc-4b15-812e-a63f3330c388"> | <img width="402" alt="Screenshot 2024-12-04 at 1 07 22 PM" src="https://github.com/user-attachments/assets/79ffdf0a-dfdd-4af9-9335-932a2af44ba7"> <img width="113" alt="Screenshot 2024-12-04 at 1 21 15 PM" src="https://github.com/user-attachments/assets/ba03a3df-b423-40bc-83bd-0e44019a23d5"> | <img width="280" src="https://github.com/user-attachments/assets/5c99c757-8575-49b3-af62-7a9dd5b1f324" /> |

So suggestions and autocorrect are controlled by the same flag, and this PR wants to be able to control them independently? @jan-swiezynski Can you confirm that your understanding is the same as mine and that this PR has the desired effect?

2024-12-04 21:32 UTC, justinmc commented on shell/platform/darwin/ios/framework/Source/FlutterTextInputPlugin.mm
> +      disableSuggestions ? UITextSpellCheckingTypeNo : UITextSpellCheckingTypeDefault;
My guess is that it wasn't possible to control these independently at the time that Flutter's enableSuggestions was added. Are we sure that's not still true? +1 to updating the docs if this change lands.

2024-12-04 21:44 UTC, jan-swiezynski commented
@justinmc Yes, exactly. The change separates autocorrect from suggestions displays and allows presenting suggestions but with autocorrect feature disabled.

2024-12-06 21:48 UTC, justinmc reviewed
I checked out this branch locally and it fixes the intended bug, but it's not possible to hide suggestions while enabling autocorrect! Is it possible to fix that as well?

| autocorrect | enableSuggestions | spellCheckConfiguration | This PR |
| --- | --- | --- | --- |
| false | false | SpellCheckConfiguration.disabled() | ✅  |
| false | false | SpellCheckConfiguration() | ✅  |
| false | true | SpellCheckConfiguration.disabled() | ✅  |
| false | true | SpellCheckConfiguration() | ✅  |
| true | false | SpellCheckConfiguration.disabled() | ❌ Suggestions appear but should not. |
| true | false | SpellCheckConfiguration() | ❌ Suggestions appear but should not. |
| true | true | SpellCheckConfiguration.disabled() | ✅  |
| true | true | SpellCheckConfiguration() | ✅  |

*Edit*: This is broken on the `main` branch as well, so I'm ok with considering this a separate issue if it's not a trivial fix.

2024-12-20 23:00 UTC, cbracken commented
Hi @jan-swiezynski is this still on your radar?

2024-12-28 20:04 UTC, jan-swiezynski commented
> Hi @jan-swiezynski is this still on your radar?

Yes, I'll get back to it in few days.

2025-01-14 17:43 UTC, jtmcdole commented
# Monorepo Migration Completed

> **TL;DR: Please migrate your PR to flutter/flutter**


The `flutter/engine` repository has been migrated to the `flutter/flutter` repository. This PR will no longer be landed here and must be migrated. To migrate your PR to the flutter repository, please follow these steps:

1. **Create a patch for this PR:**
   - Generate a patch set that represents the changes in this PR. The exact method will vary depending on your PR's history. **If your PR includes merges, it is highly recommended that you rebase it onto `main` first.**

   ```shell
   git format-patch $START_COMMIT..$END_COMMIT --stdout > combined_patch.patch
   ```

1. **Update the patch for the new engine location:**
   - The engine source code now resides in the `engine/` subdirectory within the `flutter/flutter` repository. You'll need to update the file paths in your patch accordingly.

   ```shell
   # Insert the `engine/` prefix to all paths. Note that this usage works on macOS and
   # linux versions of sed.
   sed -i.bak \
   -e 's|^\(diff --git a/\)\(.*\) b/\(.*\)|\1engine/\2 b/engine/src/flutter/\3|' \
   -e 's|^\(--- a/\)\(.*\)|\1engine/src/flutter/\2|' \
   -e 's|^\(\+\+\+ b/\)\(.*\)|\1engine/src/flutter/\2|' \
   combined_patch.patch
   ```

1. **Checkout and set up your Flutter development environment:**
   - Follow the instructions in [Setting up the Framework development environment](https://github.com/flutter/flutter/blob/master/docs/contributing/Setting-up-the-Framework-development-environment.md) to check out the `flutter/flutter` repository.
   - Remember to rename the origin remote to `upstream` (e.g., `git remote rename origin upstream`).

1. **Set up the engine development environment within the monorepo:**
   - Follow the updated instructions in [Setting up the engine environment](https://github.com/flutter/flutter/blob/master/engine/src/flutter/docs/contributing/Setting-up-the-Engine-development-environment.md), paying close attention to the changes in [gclient](https://github.com/flutter/flutter/blob/master/engine/README.md) setup and location.

1. **Apply the patch to a new branch:**
   - Create a new branch in your `flutter/flutter` repository.
   - Apply the updated patch to this branch:

   ```shell
   git apply combined_patch.patch
   ```

1. **Open a new PR:**
   - Open a new PR in the `flutter/flutter` repository with your changes.
   - Reference this original PR in the new PR's description using `flutter/engine#<PR_NUMBER>`.

___

*This is a canned message*

2025-01-14 17:43 UTC, closed without merging